### ISSUE TITLE
typescript-json-schema bin doesn't work on Linux Mint/bash

### ISSUE THREAD

**Issue by shawnExplore** [YousefED/typescript-json-schema#1]
First, glad to see someone pick up the torch from typson! 

The commandline executable `typescript-json-schema` doesn't work in Linux Mint 17.

I think this is due to the BOM at the beginning of the file. Recommend removing it. Maybe it's an artifact left by Visual Studio or something?

```
$ typescript-json-schema 
/usr/bin/typescript-json-schema: line 1: ﻿#!/usr/bin/env: No such file or directory
/usr/bin/typescript-json-schema: line 2: syntax error near unexpected token `$'{\r''
'usr/bin/typescript-json-schema: line 2: `if (process.argv[2] !== undefined && process.argv[3] !== undefined) {
```

I can submit a pr if you'd like.

**Comment by YousefED** [comment]
Thanks, should be fixed by 223eb7cf416d7fd8353fc5791b665b6d442553c4
