### ISSUE TITLE
@default be an array

### ISSUE THREAD

**Issue by navossoc** [YousefED/typescript-json-schema#100]
Hello, I would like to know if it is possible to set a default value as an array, something like this:

**Test case:**
```ts
class Test {
  /**
   * @default ["a", "b", "c"]
   */
  myKey: string[];
}
```

**Current output**
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "myKey": {
            "default": "[\"a\", \"b\", \"c]",
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "type": "object"
}
```

**Expected output:**
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "myKey": {
            "default": ["a", "b", "c"],
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "type": "object"
}
```

According to the [docs](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.2):

> 6. Metadata keywords
> 6.2. "default"
> 
> There are no restrictions placed on the value of this keyword.

Thanks for the help...

**Comment by domoritz** [comment]
Yes, this is a bug.

**Comment by navossoc** [comment]
For sure, I can give it a try...

I'm new at this project and I have a exam on the next week.
So after that I will reserve some time to take a look and find a proper way to implement it.

Is there any contribution guideline to follow or something like that?

[]'s

**Comment by navossoc** [comment]
Well, I sent a PR.  That was the best way I could think to fix this in an easy way.
Let me know what you think...
