### ISSUE TITLE
Properties marked with @ignore are still listed in required array

### ISSUE THREAD

**Issue by lfairy** [YousefED/typescript-json-schema#106]
When I mark properties with `@ignore`, I expect them to be removed from the schema altogether. But these properties still show up when I run `typescript-json-schema --required`.

Minimal test case:

```typescript
// test.ts
class Test {
    /**
     * @ignore
     */
    ignoreMe: string;
}
```

Now, when I run `typescript-json-schema tsconfig.json Test`, I'd expect this output:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
    },
    "type": "object"
}
```

But I get this instead:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
    },
    "required": [
        "ignoreMe"
    ],
    "type": "object"
}
```

I don't think this is useful behavior, because it doesn't make sense to require a property but not mention it elsewhere in the schema.

This is using `typescript-json-schema@0.10.0` with `typescript@2.1.6`.

**Comment by domoritz** [comment]
Just so I understand this correctly, this is a feature request and not a bug report, right?

**Comment by lfairy** [comment]
@domoritz In my opinion this is a bug, because I can't think of a use case for the current behavior.

**Comment by domoritz** [comment]
`@ignore` is just an arbitrary string for this library so I don't think it's a bug. I'm happy to accept a PR, though.
