### ISSUE TITLE
Specify json schema version output in $schema

### ISSUE THREAD

**Issue by mmc41** [YousefED/typescript-json-schema#109]
After upgrading the Ajv (a great schema validator) to 5.0, support for v04 of schemas are not supported by default. Hence, I would like to be able to change the $schema declaration that typescript-json-schema generates from "http://json-schema.org/draft-04/schema#" to "http://json-schema.org/draft-06/schema#". Presently typescript-json-schema has no way to override what goes into the "$schema" declaration in the generated out. Could a setting be added for this?

**Comment by domoritz** [comment]
Well, I don't think we can guarantee that we support the right semantics of every new draft. The problem is that they are not backward compatible. 

Here is how you tell AJV to use a different version

```js
const ajv = new Ajv();

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-04.json'), 'http://json-schema.org/draft-04/schema#');
```

Having said that, I'd be happy to accept a PR to add an option to change the version.
