### ISSUE TITLE
Regex for @TJS annotations is incorrect.

### ISSUE THREAD

**Issue by robertmassaioli** [YousefED/typescript-json-schema#113]
I want to write the following annotation:

    @TJS-format uri-reference

And have that put this into my URI for validation. [Here is the specification that lists it as an option](http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.7).

The problem is that the REGEX_TJS_JSDOC is incorrect. Have a look at this:

![screen shot 2017-05-24 at 1 30 36 pm](https://cloud.githubusercontent.com/assets/149178/26385767/348b602c-4085-11e7-81e4-58235ab76b4a.png)

As you can see, the \w ignores the dash separator. The simplest thing to do would be to add a dash as a valid character to the regex. Like so:

![screen shot 2017-05-24 at 1 31 40 pm](https://cloud.githubusercontent.com/assets/149178/26385799/668a4142-4085-11e7-9609-a720bcacf0f4.png)

I'll raise a PR that does that and maybe write a test too.

**Comment by robertmassaioli** [comment]
Submitted a PR for this.

**Comment by domoritz** [comment]
Fixed in https://github.com/YousefED/typescript-json-schema/pull/114
