### ISSUE TITLE
Needs better support for unions

### ISSUE THREAD

**Issue by domoritz** [YousefED/typescript-json-schema#12]

**Comment by YousefED** [comment]
can we close this / do you have more details?

**Comment by domoritz** [comment]
@mprudhom Implemented support for enums with strings. Normal enums are not yet supported but I don't know what the schema for this enums should be anyway.

**Comment by YousefED** [comment]
Ok, just as a reference you could also use:
```
/**
         * @TJS-enum ["red", "purple"]
         */
        public color: string;
```

But I suppose with the new string-literals in Typescript this isn't very interesting anymore :)
