### ISSUE TITLE
Allowing non-standard names for `tsconfig.json`

### ISSUE THREAD

**Issue by MarcusRiemer** [YousefED/typescript-json-schema#120]
I have an Angular CLI project that makes use of non-standard names for the `tsconfig.json` file. The concrete name is `tsconfig.app.json`, which results in the following error message:

    File 'scratch-sql/client/src/tsconfig.app.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

Would it be possible to soften the rules for names of project files?

**Comment by domoritz** [comment]
Can you send a pull request?
