### ISSUE TITLE
Import modules doesn't work

### ISSUE THREAD

**Issue by ramramps** [YousefED/typescript-json-schema#129]
The import modules doesn't work in the interface.
```
declare module "interface1" {
  import {test} from 'testinterface';
  export interface "testing" {
           value : test
} 
}
```
when I run this, I got cannot find module "testinterface" .

I am not sure whether I have to add any settings to make imports work.

**Comment by domoritz** [comment]
I think your exports have to be outside. The problem seems to be how you use typescript. Once you can compile typescript, this lib should generate the schema.
