### ISSUE TITLE
generated schemas do not seem to have id property

### ISSUE THREAD

**Issue by mjkkirschner** [YousefED/typescript-json-schema#141]
I am using TJS 0.14.0 and generated json schemas don't have an id property - I don't see an option to create them, is it possible or do these need to be added as a post step?

**Comment by domoritz** [comment]
What is the id property? can you send me a link to the spec?

**Comment by dmikov** [comment]
https://github.com/json-schema-org/json-schema-spec/blob/master/schema.json
Search for $id, it's a uri for type.

**Comment by nfour** [comment]
@mjkkirschner this should fix it!
