### ISSUE TITLE
Provide an example for using command line, please

### ISSUE THREAD

**Issue by Dok11** [YousefED/typescript-json-schema#143]
I talk about:
> Generate schema from a typescript type: `typescript-json-schema project/directory/tsconfig.json fully.qualified.type.to.generate`

I created my-file.ts as in tests of this repo, and run command from same folder: `typescript-json-schema tsconfig.json my-file.ts`
but I must say this commands I tried too:
```
typescript-json-schema /tsconfig.json /my-file.ts
typescript-json-schema ./tsconfig.json ./my-file.ts
```

But result is:
![image](https://user-images.githubusercontent.com/2697890/29478277-c1cca986-8474-11e7-83ca-f2462c8617e5.png)

Where is my mistake?

P.S.
typescript v2.3.4
conent of tsconfig.json:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

**Comment by domoritz** [comment]
Can you look at the tests and see how to use the API?

**Comment by Dok11** [comment]
Oh sorry, I already successfully started this from `tsc` and all fine! Thank you
