### ISSUE TITLE
Tons of resolution errors

### ISSUE THREAD

**Issue by mattoni** [YousefED/typescript-json-schema#146]
Hi, 

I'm specifying a file and an interface for which to render the schema, but no matter what file I run it on, it generates a ton of errors:
![image](https://user-images.githubusercontent.com/5110855/31059500-1952ea7a-a6b8-11e7-8926-40c3db49938a.png)
![image](https://user-images.githubusercontent.com/5110855/31059503-28334e04-a6b8-11e7-8bce-0e568b96d7c7.png)

Running with --ignore-errors works, but one thing I noticed is an extended interface is missing the properties of the base interface in the outputted schema, probably due to the resolution errors.

I have no issue compiling with typescript, and I set the same options in the settings: 
```
const compilerOptions: CompilerOptions = {
    strictNullChecks: true,
    "module": 1,
    "strict": true,
    "target": 4,
    "experimentalDecorators": true,
    "jsx": 2,
    "moduleResolution": 2,
}
```

TS version is 2.5.2, any help appreciated :)

**Comment by domoritz** [comment]
I believe that's because we are not supporting ts 2.5 yet. https://github.com/YousefED/typescript-json-schema/pull/147 will add support for ts 2.5.
