### ISSUE TITLE
Fails with empty string literal

### ISSUE THREAD

**Issue by nchen63** [YousefED/typescript-json-schema#159]
With the input:
```
export type MeasurementSuffix = "calc" | "" | "%" | "px";

export interface IBoop {
    x: MeasurementSuffix;
}
```

calling `typescript-json-schema file.ts IBoop` results in `Unsupported type:  `. Taking out the empty string fixes the issue.

**Comment by domoritz** [comment]
That looks like a bug but it's a bit surprising because the `""` and `"calc"` look almost the same in https://astexplorer.net.
