### ISSUE TITLE
CLI tool not work

### ISSUE THREAD

**Issue by wenLiangcan** [YousefED/typescript-json-schema#16]
```
/usr/bin/typescript-json-schema: line 1: ﻿#!/usr/bin/env: No such file or directory
/usr/bin/typescript-json-schema: line 2: syntax error near unexpected token `$'{\r''
/usr/bin/typescript-json-schema: line 2: `if (process.argv[2] !== undefined && process.a'gv[3] !== undefined) {
```

**Comment by wenLiangcan** [comment]
I found the closed issue #1, but seems it still not work yet.

I can start it by:
```bash
$ node /bin/typescript-json-schema 
Usage: typescript-json-schema <path-to-typescript-files> <type>
```

but can't use the executable directly.

**Comment by YousefED** [comment]
Could you retry this?

**Comment by wenLiangcan** [comment]
I tried version 0.0.4, this time I got another error message:

```
$  typescript-json-schema
/usr/bin/env: ‘node\r’: No such file or directory
```

**Comment by YousefED** [comment]
Seems to be an issue with line endings. I've now added .gitattributes to force unix-line endings. Could you try checking out the project directly from git (haven't updated npm yet), to see whether it works?

**Comment by wenLiangcan** [comment]
It works now, thank you!

**Comment by YousefED** [comment]
published fix to npm
