### ISSUE TITLE
Be able to generate schemas for all files in a folder

### ISSUE THREAD

**Issue by theigor** [YousefED/typescript-json-schema#163]
Hi,

I'm not sure if I'm just doing something wrong but I have a `./src/models` directory that has all `.ts` files. I would like to call something like `typescript-json-schema ".\src\models\**\*.ts" -o ".\src\models\json"` but `typescript-json-schema` expects an explicit type passed to it. Am I missing something?

I see the programmatic example and I can make a script that loops through all the `.ts` files in a folder - is that the only way to accomplish what I'm trying above?

Thanks!

Igor

**Comment by domoritz** [comment]
You can also just pass you `tsconfig.json` but you still need to provide a root type for the schema.

**Comment by theigor** [comment]
Right - that's the hangup. If I could specify an output directory for the json schemas like I can with `declarationDir` compiler option in tsconfig, that would be ideal. Without this, I guess I have to write a script that loops through files and outputs them one by one... or submit a PR into this project that can do this.

I'll close this for now.

**Comment by domoritz** [comment]
Yep, that seems like a special usecase. 

By the way, you can provide the type name `*`. See https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts#L984.

**Comment by theigor** [comment]
That's precisely what I was looking for. Thanks for pointing it out. 
It would be super useful to update the readme here - https://github.com/YousefED/typescript-json-schema/blame/master/README.md#L21 to something like:

* Generate schema from a typescript type: `typescript-json-schema "project/directory/**/*.ts" fully.qualified.type.to.generate.or.*.for.all.types`

**Comment by domoritz** [comment]
Can you send me a PR with an update to the Readme?

**Comment by domoritz** [comment]
Done in https://github.com/YousefED/typescript-json-schema/commit/2924c369923700538d5119052ce7b6763d8d0f4f
