### ISSUE TITLE
Error: type xyz.ts not found

### ISSUE THREAD

**Issue by RickCarlino** [YousefED/typescript-json-schema#171]
Today I installed the latest version via `npm install typescript-json-schema -g`.

To test things out, I saved the following file as `xyz.ts`:

```typescript
export interface Foo {
  bar: "Baz";
}
```

I then ran `typescript-json-schema xyz.ts *`.

It yielded the following error:

```
/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:667
            throw new Error("type " + symbolName + " not found");
            ^

Error: type xyz.ts not found
    at JsonSchemaGenerator.getSchemaForSymbol (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:667:19)
    at generateSchema (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:823:32)
    at exec (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:853:22)
    at Object.run (/usr/lib/node_modules/typescript-json-schema/typescript-json-schema.js:903:5)
    at Object.<anonymous> (/usr/lib/node_modules/typescript-json-schema/bin/typescript-json-schema:3:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Although I was not able to get `*` to work locally, I _was_ able to get it to work via `typescript-json-schema xyz.ts Foo`.

Here is my `tsconfig.json` for reference:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": false,
    "moduleResolution": "node"
  }
}
```

Thanks for maintaining this very useful library!

**EDITS:** Typo in filename from previous attempts, updated title to reflect more isolated case.

**Comment by domoritz** [comment]
Does this happen with older versions as well?

**Comment by RickCarlino** [comment]
@domoritz I tried every version going back to `0.16.0`. The issue started after v0.16.0. When running on `0.16.0` I got a different error:

```
// this error is repeated many times:
/blah/blah/node_modules/@types/node/index.d.ts (123,456): Cannot find name 'Promise'.
```
Adding `"es2016.promise"` to `tsconfig.json` did not fix the issue.

Please let me know if you need any other information.

**Comment by domoritz** [comment]
I thought this may be related to https://github.com/YousefED/typescript-json-schema/pull/170 but looks like it's not.

**Comment by noahtkeller** [comment]
For anyone else that may stumble across this, you should place the asterisk inside quotes:

```
$ typescript-json-schema tsconfig.json "*"
```

Without the quotes the shell recognizes it as a wildcard and passes each file in the $PWD as an additional argument. Resulting in something like:

```
$ typescript-json-schema tsconfig.json somefile.js someotherfile.js anotherfile.js
```

I don't think this is a bug with the software.

**Comment by domoritz** [comment]
Thank you @noahtkeller
