### ISSUE TITLE
Unclear from docs if optional compilerOptions override sane defaults

### ISSUE THREAD

**Issue by ORESoftware** [YousefED/typescript-json-schema#174]
I see this in the readme:

```js
// optionally pass ts compiler options
const compilerOptions = {
    strictNullChecks: true
}
```

to me, it's unclear if these options are used to override sane defaults or what?

is this a correct way of doing it programmatically?

```js
const tsconfig = require('../tsconfig.json');
const compilerOptions = Object.assign(tsconfig, {
    strictNullChecks: true
});
```

should I load my tsconfig.json file programmatically? I assume yes?

**Comment by domoritz** [comment]
Options get merged in https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts#L894.
