### ISSUE TITLE
Support question - works at command line, but cannot get it to work programmatically

### ISSUE THREAD

**Issue by ORESoftware** [YousefED/typescript-json-schema#175]
With this project as context:
https://github.com/sumanjs/suman-types

I can generate a schema using:

`$ typescript-json-schema --ignoreErrors tsconfig.json IAtConfig`

however, I tried doing this programmatically:
https://github.com/sumanjs/suman-types/blob/master/schemas/generate-schemas.js

but when you run that script, I keep getting a `null` schema.

If you have time, maybe clone the repo and try running:

`$ node schemas/generate-schema.js`

**Comment by domoritz** [comment]
Please check how we call the library programmatically in https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts#L1012.
