### ISSUE TITLE
Upgrade to TypeScript 2.7.1 or 2.7.2

### ISSUE THREAD

**Issue by curledUpSheep** [YousefED/typescript-json-schema#182]
With more and more libraries upgrading to 2.7, it would be nice to have this one updated as well.

I actually have a specific use case where I need to load TypeScript source code from a string, doing some funky stuff with a customized CompilerHost to create a Program. Because my workspace is using TypeScript 2.7.1, the generated Program is not compatible with TJS (it seems they changed some SyntaxKind values since 2.6.2, although I'm not sure if that actually causes the issue).
If I just take the `typescript-json-schema.ts` source code and put it next to the rest of my code, everything seems to work just fine.

**Comment by domoritz** [comment]
I keep https://github.com/vega/ts-json-schema-generator up to date. I'm happy to accept pull requests to update this library.
