### ISSUE TITLE
Support json-schema draft7?

### ISSUE THREAD

**Issue by kirillgroshkov** [YousefED/typescript-json-schema#184]
Any plans to support recent specification of json-schema?

I need it, because e.g when I'm using the most popular json-schema validator - it requires many untrivial steps to convert draf4 to draft7 to make it work. To my understanding, differences between draft4 and draft7 are not that big, so should be not very hard, but should benefit a lot of people to have the recent specification supported.

**Comment by MarcusRiemer** [comment]
Did you see the related discussion in issue #156?

**Comment by domoritz** [comment]
Let's move to draft 6. Draft 7 is not well supported yet.

**Comment by kirillgroshkov** [comment]
draft6 will do!

**Comment by domoritz** [comment]
Just released 0.21.0

**Comment by kirillgroshkov** [comment]
0.21.0 works like charm! Thanks a lot!
