### ISSUE TITLE
Create option to omit $schema prop

### ISSUE THREAD

**Issue by ORESoftware** [YousefED/typescript-json-schema#206]
this line in my schema:

 "$schema": "http://json-schema.org/draft-06/schema#",

is causing problems when using AJV to read the schema. I get this error:

> ```
> Error: no schema with key or ref "http://json-schema.org/draft-06/schema#"
> ```

Is there an option to omit that line? Is it necessary?

Specifically it throws here:

```console
.../node_modules/ajv/lib/ajv.js:92
    if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
```

when I use this code:

```js
import AJV = require('ajv')
const ajv = new AJV();
ajv.validate(schema,data);
```

where AJV is version:
`   "ajv": "^6.4.0"`

and the TJS version is:
`0.23.0`

**Comment by domoritz** [comment]
You can add the meta schema as in https://github.com/YousefED/typescript-json-schema/blob/master/test/schema.test.ts#L9.
