### ISSUE TITLE
v0.24.0 release?

### ISSUE THREAD

**Issue by arielshaqed** [YousefED/typescript-json-schema#213]
I'd really like to be able to pull a version with #211 from NpmJS (right now I'm using [@almonds/typescript-json-schema](https://www.npmjs.com/package/@almonds/typescript-json-schema, which will eventually add public confusion).
Is there a plan for releasing it sometime soon?  I'd be happy to help (e.g. if some issues are needed to release).

**Comment by arielshaqed** [comment]
Suggesting "0.24.0" because 0.23.0 is out on NpmJS, even though it's untagged on this repo.

**Comment by domoritz** [comment]
Done. Give it a spin.
