### ISSUE TITLE
Support for draft version 7

### ISSUE THREAD

**Issue by larsbuch** [YousefED/typescript-json-schema#221]
It would be nice to have support for generating draft 7 schemas

**Comment by domoritz** [comment]
There is no wide support for it yet. We could pretend to generate draft 7 but wouldn't use any of the features. In fact, we are still generating draft 4 schemas, I think.

**Comment by maneetgoyal** [comment]
@domoritz Is draft 4 still possible via this package? Or will it only generate draft 7? Some schema we have is in draft 4, so was wondering. Didn’t find anything in readme. Sorry if I missed it.

**Comment by suzil** [comment]
I was also trying to figure it out. Amazon EventBridge Schema Registry only supports draft 4 currently.
