### ISSUE TITLE
Using TJS with Ajv, and TJS outputs version 6 instead of version 7 schema

### ISSUE THREAD

**Issue by ORESoftware** [YousefED/typescript-json-schema#227]
When I use TJS like so:

```bash
typescript-json-schema  --ignoreErrors  'src/index.ts' NppJSONRootConf > assets/schema/npp.root.json
typescript-json-schema  --ignoreErrors  'src/index.ts' NppJSONConf > assets/schema/npp.json
```

my schema get generated, but with an older draft version:

    "$schema": "http://json-schema.org/draft-06/schema#",

when I use the schema with [Ajv](https://github.com/epoberezkin/ajv), I then get an error saying:

> /home/oleg/WebstormProjects/oresoftware/npp/node_modules/ajv/lib/ajv.js:92
>     if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
> 

in order to get it to work, I have to manually update the schema, and insert:

```
"$schema": "http://json-schema.org/draft-07/schema#",
```

Can TJS be updated to output version 7 instead of version 6? Can we control which version we output?

**Comment by domoritz** [comment]
You asked this question before and I answered it in https://github.com/YousefED/typescript-json-schema/issues/205#issuecomment-385548381 ;-)
