### ISSUE TITLE
Issue with TypeScript 1.8 dependency when there are .d.ts declarations

### ISSUE THREAD

**Issue by mprudhom** [YousefED/typescript-json-schema#23]
When a project contains .d.ts typings, schema generation fails with the error:

```
/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:39567
                throw e;
                ^

TypeError: Cannot read property 'replace' of undefined
    at Object.normalizeSlashes (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:1383:20)
    at writeReferencePath (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:31876:90)
    at /private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:30442:29
    at Object.forEach (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:938:30)
    at /private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:30434:20
    at Object.forEach (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:938:30)
    at emitDeclarations (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:30427:12)
    at getDeclarationDiagnosticsFromFile (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:30393:13)
    at onSingleFileEmit (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:6380:13)
    at Object.forEachExpectedEmitFile (/private/tmp/ts/typescript-json-schema/node_modules/typescript/lib/typescript.js:6369:21)
```

The issue seems to be the call to `getDeclarationDiagnostics` is failing with the error. I don't have enough insight into the typescript compiler, but it looks like a path is not being provided somewhere. The only workaround I can find is to revert the typescript dependency from 1.8.0 to 1.7.5, but someone who knows the typescript transpiler better might have more insight in how to work around it.

**Comment by YousefED** [comment]
Thanks. Before I dig in, what command are you running exactly?

Does this also fail with the tests? I assume not since I don't think there are .d.ts files in the tests right?

**Comment by mprudhom** [comment]
Here's a command that will reproduce the error:

```
git clone https://github.com/YousefED/typescript-json-schema.git && git clone https://github.com/vega/vega-lite.git && cd typescript-json-schema && npm build && npm install && ./bin/typescript-json-schema ../vega-lite/src/spec.ts Spec
```

**Comment by YousefED** [comment]
I believe the problem is we shouldn't always call getDeclarationDiagnostics.

Steps to fix:
1) use ts.getPreEmitDiagnostics() to collect all diagnostics messages (instead of diagnostics = [....])
2) set declaration:false similar to the tsconfig.json in vega-lite. A better way would be to load the actual tsconfig.json from the project we're generating schemas from. This can be done with var conf = ts.convertCompilerOptionsFromJson(null, "file\\to\\vega-lite\\", "tsconfig.json"); instead of hardcoding ts.CompilerOptions in generateSchema

I had just enough time to find the cause, but am running out of time to nicely implement the fix atm. I can do it later or you should be able to fix it with above directions assuming I'm correct :)

**Comment by YousefED** [comment]
This is fixed now IF you pass tsconfig.json to TJS.

If this is undesirable, we need to do one of:
1) change the default compiler options to include declaration:false. I'm not sure what the consequences of this are.
2) extend "args" to include options to be passed to the typescript compiler, so you can manually set declaration = false

**Comment by simonh1000** [comment]
I have just got the same error message compiling Angular2 wtih ahead of time.

My tsconfig.json file already had
```
{
  "compilerOptions": {
    "declaration": false,
```
which seems to be the recommendation above. 

angular-cli: 1.0.0-beta.18
node: 6.7.0
os: linux x64   (also had the same with OSX)

**Comment by domoritz** [comment]
@simonh1000 make sure that you don't have any `.d.ts` files lying around.
