### ISSUE TITLE
More than one ReadonlyArray type definition 

### ISSUE THREAD

**Issue by bruceflowers** [YousefED/typescript-json-schema#237]
Great project guys! 

I'm noticing a weird behavior with typed `ReadonlyArray`s. When there are two or more definitions with different generics provided, the cli tool output points to a single ref, `"ReadonlyArray"`, which is only correct for one of them:

(TypeScript 3.0 and typescript-json-schema 0.31.0)

```
interface A {
    a: ReadonlyArray<string>;
}
interface B {
    b: ReadonlyArray<number>;
}

export type SomeType = B | A;
```

The output:

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "anyOf": [
        {
            "$ref": "#/definitions/A"
        },
        {
            "$ref": "#/definitions/B"
        }
    ],
    "definitions": {
        "A": {
            "additionalProperties": false,
            "properties": {
                "a": {
                    "$ref": "#/definitions/ReadonlyArray"
                }
            },
            "required": [
                "a"
            ],
            "type": "object"
        },
        "B": {
            "additionalProperties": false,
            "properties": {
                "b": {
                    "$ref": "#/definitions/ReadonlyArray"
                }
            },
            "required": [
                "b"
            ],
            "type": "object"
        },
        "ReadonlyArray": {
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    }
}
```

Also, defining type aliases for each array like this:

`type MyStringArray = ReadonlyArray<string>`

doesn't produce a different result; the typealias definitions still point back to a single ReadonlyArray definition as in the above.

**Comment by domoritz** [comment]
Can you try https://github.com/vega/ts-json-schema-generator and see whether you get the same error?

**Comment by domoritz** [comment]
I think this should be easy to fix (since you don't want to fix aliases in general but one specific case) but I currently don't have the cycles to dive into it. I'm happy to review a pull request, though. I'm sure you can fix it less than a day.

**Comment by bruceflowers** [comment]
@domoritz I'd like to fix this now, but sadly I also have time pressures at the moment. In the meantime, I realized that for our purposes, we don't exactly need to have shared refs for every alias (the schema file will only be used by machines, not people), so running the tool without the `--aliasRefs` arg does the trick for now. Leaving this here in case anyone else encounters the same issue and needs a workaround.

**Comment by bruceflowers** [comment]
Looks like this is working in the latest version `v0.40.0`. Closing.
