### ISSUE TITLE
Simple usage?

### ISSUE THREAD

**Issue by dakom** [YousefED/typescript-json-schema#238]
I tried various approaches, and I keep getting commandline errors

I have a project with a `tsconfig.json` and lots of stuff under `src`

However, I only want to generate a schema from `src/types/game/GameInstance.ts` - starting from the root object of "interface Game {...}"

What is the correct commandline usage to do so?

**Comment by ORESoftware** [comment]
@dakom  try this command:

```bash
$ npm i -g typescript-json-schema   # install globally

$ typescript-json-schema --ignoreErrors 'lib/index.ts' NluConf   # run it 
```

the above command will write to stdout.... use redirection to send it to a file. what it does is look for the NluConf interface in the lib/index.ts file, and then generate a schema based off that interface.

**Comment by dakom** [comment]
Yup, that worked - thanks!
