### ISSUE TITLE
When tool fails with "Unable to write output file" exit with non-zero exit code

### ISSUE THREAD

**Issue by palfrey** [YousefED/typescript-json-schema#239]
Right now, even though it failed (in my particular case with `Unable to write output file: EACCES: permission denied, open 'scenarioConfig.json'`) it exits with code 0, which makes it hard to work with in CI/programmatic environments. Can it please be changed to have a non-zero exit code?

**Comment by domoritz** [comment]
Can you send a PR?

**Comment by domoritz** [comment]
Just the ts changes. Thanks!
