### ISSUE TITLE
tjs throws error:  throw new Error("type " + symbolName + " not found");  in Bamboo

### ISSUE THREAD

**Issue by geetee24** [YousefED/typescript-json-schema#243]
Can you provide reason for this error that occurs in bamboo and not in a local pc ?
tjs version "0.24.1"

ntral@1.3.0 generate-valid-json-schemas /root/bamboo-agent-home/xml-data/build-dir/GREEN-BRC-JOB1
04-Sep-2018 16:37:06 | > typescript-json-schema "src/app/services/non-core/data/**/*.object.ts" * --ignoreErrors --out ./src/json_schema/json_schema.json --noExtraProps true  --required true && node ./bat/lib/save_json_schema.js
04-Sep-2018 16:37:06 |  
04-Sep-2018 16:37:11 | /root/bamboo-agent-home/xml-data/build-dir/GREEN-BRC-JOB1/node_modules/typescript-json-schema/typescript-json-schema.js:763
04-Sep-2018 16:37:11 | throw new Error("type " + symbolName + " not found");
04-Sep-2018 16:37:11 | ^
04-Sep-2018 16:37:11 |  
04-Sep-2018 16:37:11 | Error: type ChangeLog.md not found
04-Sep-2018 16:37:11 | at JsonSchemaGenerator.getSchemaForSymbol (/root/bamboo-agent-home/xml-data/build-dir/GREEN-BRC-JOB1/node_modules/typescript-json-schema/typescript-json-schema.js:763:19)
04-Sep-2018 16:37:11 | at generateSchema (/root/bamboo-agent-home/xml-data/build-dir/GREEN-BRC-JOB1/node_modules/typescript-json-schema/typescript-json-schema.js:911:26)
04-Sep-2018 16:37:11 | at Object.exec (/root/bamboo-agent-home/xml-data/build-dir/GREEN-BRC-JOB1/node_modules/typescript-json-schema/typescript-json-schema.js:953:22)
04-Sep-2018 16:37:11 | at Object.run (/root/bamboo-agent-home/xml-data/build-dir/GREEN-BRC-JOB1/node_modules/typescript-json-schema/typescript-json-schema-cli.js:43:30)
04-Sep-2018 16:37:11 | at Object.<anonymous> (/root/bamboo-agent-home/xml-data/build-dir/GREEN-BRC-JOB1/node_modules/typescript-json-schema/bin/typescript-json-schema:3:5)
04-Sep-2018 16:37:11 | at Module._compile (module.js:571:32)
04-Sep-2018 16:37:11 | at Object.Module._extensions..js (module.js:580:10)
04-Sep-2018 16:37:11 | at Module.load (module.js:488:32)
04-Sep-2018 16:37:11 | at tryModuleLoad (module.js:447:12)
04-Sep-2018 16:37:11 | at Function.Module._load (module.js:439:3)
04-Sep-2018 16:37:11 |  
04-Sep-2018 16:37:11 | npm ERR! Linux 3.10.0-862.3.3.el7.x86_64
04-Sep-2018 16:37:11 | npm ERR! argv "/opt/node-v7.10.0-linux-x64/bin/node" "/opt/node-v7.10.0-linux-x64/bin/npm" "run" "generate-valid-json-schemas"
04-Sep-2018 16:37:11 | npm ERR! node v7.10.0
04-Sep-2018 16:37:11 | npm ERR! npm  v4.2.0
04-Sep-2018 16:37:11 | npm ERR! code ELIFECYCLE
04-Sep-2018 16:37:11 | npm ERR! errno 1
04-Sep-2018 16:37:11 | npm ERR! trinet-browser-central@1.3.0 generate-valid-json-schemas: `typescript-json-schema "src/app/services/non-core/data/**/*.object.ts" * --ignoreErrors --out ./src/json_schema/json_schema.json --noExtraProps true  --required true && node ./bat/lib/save_json_schema.js`
04-Sep-2018 16:37:11 | npm ERR! Exit status 1
04-Sep-2018 16:37:11 | npm ERR!
04-Sep-2018 16:37:11 | npm ERR! Failed at the trinet-browser-central@1.3.0 generate-valid-json-schemas script 'typescript-json-schema "src/app/services/non-core/data/**/*.object.ts" * --ignoreErrors --out ./src/json_schema/json_schema.json --noExtraProps true  --required true && node ./bat/lib/save_json_schema.js'.
04-Sep-2018 16:37:11 | npm ERR! Make sure you have the latest version of node.js and npm installed.
04-Sep-2018 16:37:11 | npm ERR! If you do, this is most likely a problem with the trinet-browser-central package,
04-Sep-2018 16:37:11 | npm ERR! not with npm itself.
04-Sep-2018 16:37:11 | npm ERR! Tell th

**Comment by domoritz** [comment]
You need to pass in the type that you want to export. Not sure where the `ChangeLog.md` in your errors comes from. 

Please note that github issues are not for questions but bug reports and feature requests.

**Comment by geetee24** [comment]
thank you I do not understand your comment.   it works fine in local pc. fails in bamboo porocess.  same source code.

What /where pass in what type?   

This is proper place to report a bug.

**Comment by domoritz** [comment]
I have never heard of or used bamboo porocess so I can't help but would say the error is there since it works locally.
