### ISSUE TITLE
Schema for object with number index

### ISSUE THREAD

**Issue by CaselIT** [YousefED/typescript-json-schema#245]
The typescript type
```ts
interface MyType {
  [index: number]: number
}
```
is parsed into the schema
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "items": {
        "type": "number"
    },
    "type": "array"
}
```
while it should be parsed into
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "patternProperties": {
        "^[0-9]+$": {
            "type": "number"
        }
    },
    "additionalProperties": false
}
```

**Comment by domoritz** [comment]
Yeah, that is weird. Can you send a PR to fix it?

**Comment by CaselIT** [comment]
I can try, but I do not know when I will have the time

**Comment by domoritz** [comment]
Thanks!

**Comment by CaselIT** [comment]
Do you think the current behaviour should be kept under a switch?

**Comment by domoritz** [comment]
It looks incorrect to me. If we don't have a test for it, probably no.

**Comment by CaselIT** [comment]
I've found the time to look into fixing this. I've added a pull request that fixes this
