### ISSUE TITLE
Add support for `unknown` type

### ISSUE THREAD

**Issue by DerJacques** [YousefED/typescript-json-schema#256]
Thank you for this great package!

Since version 3.0, Typescript supports the `unknown` type ([Release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html)).

`typescript-json-schema` does not yet support this type when converting to JSON.
I believe it should be added here:
https://github.com/YousefED/typescript-json-schema/blob/c0c7e2e0f128cb1321fbab37b5cc9e2bc6f1f503/typescript-json-schema.ts#L408

I think it would make sense to handle it exactly like `any`, since it basically allows for all types (but the consumer has to check them manually).

I am happy to create a PR if the above line is the only line that needs to be updated. But I do not know if there are any other spots that should be updated.

**Comment by domoritz** [comment]
Yeah, unknown is like any. You can add a test in your pr and see whether changing that one line is sufficient.

**Comment by HoldYourWaffle** [comment]
Shouldn't this be closed now that #278 is merged?

**Comment by domoritz** [comment]
Yes, thanks!
