### ISSUE TITLE
TypeError: Unsupported type: symbol

### ISSUE THREAD

**Issue by philipp-sorin** [YousefED/typescript-json-schema#257]
Command fails with next error:

/Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:312
                    throw error;
                    ^

TypeError: Unsupported type: symbol
    at JsonSchemaGenerator.getDefinitionForRootType (/Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:310:33)
    at JsonSchemaGenerator.getTypeDefinition (/Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:767:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:339:31)
    at /Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:613:37
    at Array.reduce (<anonymous>)
    at JsonSchemaGenerator.getClassDefinition (/Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:611:45)
    at JsonSchemaGenerator.getTypeDefinition (/Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:777:26)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:339:31)
    at /Users/filippsorin/.nvm/versions/node/v8.8.0/lib/node_modules/typescript-json-schema/typescript-json-schema.js:613:37
    at Array.reduce (<anonymous>)

**Comment by nicksrandall** [comment]
I'm also running into this. Looking into a fix.

**Comment by wSedlacek** [comment]
I was able to fix this error with the following patch.

```diff
diff --git a/node_modules/typescript-json-schema/dist/typescript-json-schema.js b/node_modules/typescript-json-schema/dist/typescript-json-schema.js
index c6e40bc..7464c63 100644
--- a/node_modules/typescript-json-schema/dist/typescript-json-schema.js
+++ b/node_modules/typescript-json-schema/dist/typescript-json-schema.js
@@ -437,6 +437,9 @@ var JsonSchemaGenerator = (function () {
             else if (flags & ts.TypeFlags.Boolean) {
                 definition.type = "boolean";
             }
+            else if (flags & ts.TypeFlags.ESSymbol) {
+                definition.type = "symbol";
+            }
             else if (flags & ts.TypeFlags.Null) {
                 definition.type = "null";
             }
diff --git a/node_modules/typescript-json-schema/typescript-json-schema.ts b/node_modules/typescript-json-schema/typescript-json-schema.ts
index 2d4a741..e6cca50 100644
--- a/node_modules/typescript-json-schema/typescript-json-schema.ts
+++ b/node_modules/typescript-json-schema/typescript-json-schema.ts
@@ -647,6 +647,8 @@ export class JsonSchemaGenerator {
                 definition.type = isInteger ? "integer" : "number";
             } else if (flags & ts.TypeFlags.Boolean) {
                 definition.type = "boolean";
+            } else if (flags & ts.TypeFlags.ESSymbol) {
+                definition.type = "symbol";
             } else if (flags & ts.TypeFlags.Null) {
                 definition.type = "null";
             } else if (flags & ts.TypeFlags.Undefined) {
```

**Comment by LeoJ-cn** [comment]
> I was able to fix this error with the following patch.
> 
> ```diff
> diff --git a/node_modules/typescript-json-schema/dist/typescript-json-schema.js b/node_modules/typescript-json-schema/dist/typescript-json-schema.js
> index c6e40bc..7464c63 100644
> --- a/node_modules/typescript-json-schema/dist/typescript-json-schema.js
> +++ b/node_modules/typescript-json-schema/dist/typescript-json-schema.js
> @@ -437,6 +437,9 @@ var JsonSchemaGenerator = (function () {
>              else if (flags & ts.TypeFlags.Boolean) {
>                  definition.type = "boolean";
>              }
> +            else if (flags & ts.TypeFlags.ESSymbol) {
> +                definition.type = "symbol";
> +            }
>              else if (flags & ts.TypeFlags.Null) {
>                  definition.type = "null";
>              }
> diff --git a/node_modules/typescript-json-schema/typescript-json-schema.ts b/node_modules/typescript-json-schema/typescript-json-schema.ts
> index 2d4a741..e6cca50 100644
> --- a/node_modules/typescript-json-schema/typescript-json-schema.ts
> +++ b/node_modules/typescript-json-schema/typescript-json-schema.ts
> @@ -647,6 +647,8 @@ export class JsonSchemaGenerator {
>                  definition.type = isInteger ? "integer" : "number";
>              } else if (flags & ts.TypeFlags.Boolean) {
>                  definition.type = "boolean";
> +            } else if (flags & ts.TypeFlags.ESSymbol) {
> +                definition.type = "symbol";
>              } else if (flags & ts.TypeFlags.Null) {
>                  definition.type = "null";
>              } else if (flags & ts.TypeFlags.Undefined) {
> ```

Thanks, this worked

**Comment by domoritz** [comment]
Wanna send a pull request?

**Comment by historydev** [comment]
Answer for all types:
`else if(propertyTypeString) {
				for(let key in ts.TypeFlags) {
					if(key.toLowerCase() === propertyTypeString) {
						console.log(key);
						definition.type = key;
					}
				}
			}`
