### ISSUE TITLE
feature request: support `@examples` annotation -> json schema `examples`

### ISSUE THREAD

**Issue by evaneus** [YousefED/typescript-json-schema#259]
It seems that `@description` and `@default` keywords are supported but not `@examples` (or @title)

https://json-schema.org/understanding-json-schema/reference/generic.html

**Comment by domoritz** [comment]
These were added in draft 6 so we could support them now. Want to send a PR?

**Comment by evaneus** [comment]
Not sure if I did that correctly, but PR submitted.
