### ISSUE TITLE
description for Date type property is not shown in output

### ISSUE THREAD

**Issue by sakai-y** [YousefED/typescript-json-schema#263]
I made a code below:
```typescript
export interface Response {
  /**
   * the date for ticker expired.
   */
  expirationDate: Date;
}
```

`typescript-json-schema` generates following...
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "expirationDate": {
      "description": "Enables basic storage and retrieval of dates and times.",
      "type": "string",
      "format": "date-time"
    }
}
````

as above, the `description` for `Date` type property is always `Enables basic storage and retrieval of dates and times.`. Is this intended behaviour ?

**Comment by domoritz** [comment]
Hmm, there is a conflict between the description of date a d your custom comment. We prefer to take the comment from the most specific type but I think it should be the least specific as you point out here. 

Would you like to send a PR to fix this bug?

**Comment by sakai-y** [comment]
Yes, I will try.
