### ISSUE TITLE
Better examples & documentation

### ISSUE THREAD

**Issue by YousefED** [YousefED/typescript-json-schema#27]
- document TJS-\* properties which can be set via comments
- document advanced examples
- explain + demo some use cases to demonstrate value

**Comment by melke** [comment]
Hey! Thanks for creating this project, I love it. Looking forward to more docs.

**Comment by YousefED** [comment]
Thanks! Any particular examples / docs you're looking for?

Any use cases you're doing and might be useful for turning into an example?

**Comment by sueess** [comment]
Im wondering if there is any way to annotate the Typescript file so it generates something like that:
"type": ["string", "null"]. Can i somehow define this "nullable"-Property? Thanks a lot!

**Comment by YousefED** [comment]
@sueess  could you add this as a separate issue for us to look into? Thanks!

**Comment by melke** [comment]
Hi, it would be nice if there were a larger example, including a tsconfig.json in the example folder and some examples of how to run the tool with different options. I also have a problem generating enum types. For example, an enum type of strings in TS get translated to a simple string without the enum string values. Am I doing something wrong?

**Comment by felixfbecker** [comment]
Programmatic usage 😉

**Comment by Dok11** [comment]
@YousefED maybe you will be interested:
![image](https://user-images.githubusercontent.com/2697890/29476613-7c2deeaa-846d-11e7-9494-80a9dc1f9c9e.png)
