### ISSUE TITLE
'format' key is not supported by Mongo

### ISSUE THREAD

**Issue by alexarvanitidisalpha** [YousefED/typescript-json-schema#273]
As explained here: https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/#omissions the `format` key is not currently supported by MongoDB. We generate the schemata for Mongo using `typescript-json-schema` and there's currently no way to avoid this `format` key on the json schema generated. Is there any flag that could do this?

**Comment by domoritz** [comment]
Not yet, no. You could post-process the output.

**Comment by alexarvanitidisalpha** [comment]
We used the following node script as a post processor for Mongo, if anyone wants to re-use it or @domoritz if you want to include it in the `readme.md`.

`#!/usr/bin/env node

const UNWANTED_JSON_KEYS = ["$schema"];

process.stdin.resume();
process.stdin.setEncoding("utf8");

/**
 * Removes unwanted keys from the generated json for the mongo schema
 * https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/
 * The library we're using is not generating mongo friendly schema
 */
function removeUnwantedKeys(json) {
  UNWANTED_JSON_KEYS.forEach(key => delete json[key]);

  if (json.format === "date-time") {
    json.bsonType = "date";
    delete json.type;
    delete json.format;
  }

  Object.values(json).forEach((nestedObj) => {
    const isObject = json instanceof Object;
    if (isObject) {
      removeUnwantedKeys(nestedObj);
    }
  });
}

process.stdin.on("data", async (data) => {
  const json = JSON.parse(data);

  removeUnwantedKeys(json);

  process.stdout.write(JSON.stringify(json, null, 2) + "\n");
});`
