### ISSUE TITLE
Support openapi style JSON schema output

### ISSUE THREAD

**Issue by robaca** [YousefED/typescript-json-schema#287]
In OpenAPI 3 documents, `"type": ["null", "string"]` is not supported. Instead you have to specify a property via `"type": "string", "nullable": true"`

Please provide a command line argument to optimize the output for OpenAPI 3 compatibility.

**Comment by domoritz** [comment]
As far as I know, `nullable` is not a valid JSON schema property. Unless I am missing something, it is not possible to do this, unfortunately.
