### ISSUE TITLE
Ignore a specific property

### ISSUE THREAD

**Issue by timini** [YousefED/typescript-json-schema#299]
```
import { EChartOption } from "echarts";
import { AppName } from "../../../interfaces";

export interface IOwnProps {
  /**
   * @ignore
   */
  options?: EChartOption | EChartOption[];
  filterName?: string;
  appName: AppName;
  graphName: string;
}
```

EChartsOptions is a massive type and causes generator.getSchemaForSymbol to throw an error, In this case I would be happy to force the function to generate a schema without this property and thus avoid the error. I cant find an escape hatch which allows me to ignore a type whilst still getting back the rest of the schema

**Comment by dobesv** [comment]
Did you try `@TJS-ignore` ?  Just a random idea...

**Comment by loopingz** [comment]
The @ignore option works for me with small types, I have a big type that generates an issue also. The @ignore is applied after the resolution, so it does not prevent the error

**Comment by domoritz** [comment]
Fixed in https://github.com/YousefED/typescript-json-schema/pull/390
