### ISSUE TITLE
using $ref in generated schema

### ISSUE THREAD

**Issue by shawnExplore** [YousefED/typescript-json-schema#3]
typson seems to use `$ref` by default to refer to other types.

typescript-json-schema defaults to defining one big json-schema type with the dependencies defined inline.

Does tjs (typescript-json-schema; too long to type) support this style or is it planned? I was expecting it to output something very similar to typson by default?

**Comment by EToreo** [comment]
+1 to $ref

**Comment by domoritz** [comment]
Would love to see this implemented. This would make tjs a great alternative to typson.

**Comment by YousefED** [comment]
Agree! Only steps needed:
- Keep a Map of types processed
- Add support for options / flags
- If options.ref is set, always use $ref and the Map instead of serializing types recursively

@domoritz is this on your list or shall I look into it?

**Comment by domoritz** [comment]
Its not on my list and I'm out of the country for a few weeks so go ahead.
This would be a great feature!

**Comment by YousefED** [comment]
This has been added in https://github.com/YousefED/typescript-json-schema/tree/%24ref-support

it's enabled by default in that branch, (const useRef = true;). Would be nice to make this an option by supporting a flag to turn this on. If anyone could add a generic flags / options system (so we can also support other optional features), I'll merge this branch with master.

**Comment by domoritz** [comment]
Fantastic. I'll try this when I'm back.

**Comment by domoritz** [comment]
I can add options to the program. However, I have a few questions about the ref code.

1. When you have classes/interfaces with the same name in different contexts, they get merged. I tried to have an interface with the same name in two different classes and ended up with the same reference in both places.
2. Having a top level $ref seems unnecessary. Can you change the code so that it does not use a reference?
3. What happens if there are circular references (for example in a linked list)? With $ref, this shouldn't be a problem but I suspect that something bad happens when we don't use references.

**Comment by YousefED** [comment]
1) good point. I namespaced everything in my code so didn't run into this issue. I'll try to add logic to fix this issue
2) should be easy by changing line 244 to:
    let def = this.getClassDefinition(this.allSymbols[clazzName], this.tc, false);
(maybe nice to set this as an option)
3) excellent find, I suppose the current code will loop infinitely. My suggestion would be to not add any logic at this moment to try to detect this. Seems overkill / low-prio at the moment. Instead, I suggest setting the useRef option to true by default. Users will then run into it only when they change the flag.

**Comment by mprudhom** [comment]
I added simplistic command-line flag parsing for using refs and the ability to no use a reference for the root element at https://github.com/YousefED/typescript-json-schema/pull/15

**Comment by domoritz** [comment]
What's left to do before https://github.com/YousefED/typescript-json-schema/tree/%24ref-support can be merged?

**Comment by YousefED** [comment]
Good point, merging now!
