### ISSUE TITLE
Generate Javascript

### ISSUE THREAD

**Issue by mtiller** [YousefED/typescript-json-schema#302]
It would be very nice to have the definitions generated as Javascript.  This way, the schemas could be generated as part of the build process for a module and included among the package sources.  This would, in turn, allow other packages to import the JSON schemas for types found in a package.  This would be useful because it would bring a means of runtime validation.

It seems reasonable to add something like `--asVar x` as a command line argument.  The only impact in terms of the schema generation would be something like this:

```typescript
  const json = stringify(definition, {space: 4}) + "\n\n";
  json = args.asVar ? `exports = { "${args.asVar}": ${json} }` : json;
```

If you'd consider this, I can submit a PR.

**Comment by domoritz** [comment]
I feel this would be something you can easily do if you import the schema generator in a node module that calls the API directly. What do you think?

**Comment by mtiller** [comment]
Sure.  You can even do what I ultimately wound up doing, running it through a `sed` script:

```
$ typescript-json-schema ./tsconfig.json "*" | sed "1s;^;exports.schemas=;"
```
