### ISSUE TITLE
How to validate json file with json-schema

### ISSUE THREAD

**Issue by ORESoftware** [YousefED/typescript-json-schema#306]
Alright so I used this:

```bash
$ typescript-json-schema  declarations.ts InterosEventsConfig -o json-schema.json
```

later on, I want to validate a json file with what's in json-schema.json

so I want to do something like:

```bash
$ typescript-json-schema --validate 'x.json' --according-to 'json-schema.json'
```

is there some way to validate things with this tool, or should I use a different tool to validate json against a schema?

**Comment by ORESoftware** [comment]
I guess this is one way to do it:

http://xmodulo.com/validate-json-command-line-linux.html

but I hate python and would rather just use another tool

**Comment by domoritz** [comment]
I highly recommend https://github.com/epoberezkin/ajv if you are in JavaScript.
