### ISSUE TITLE
Suggestion: make the generator engine external module

### ISSUE THREAD

**Issue by Bnaya** [YousefED/typescript-json-schema#31]
It would be nice if the generator was external node module, usable as in javascript code.
I'm thinking about generating my schemes dynamically from the ts on build time as webpack loader or so.
And also will be usable as gulp task

**Comment by YousefED** [comment]
You should be able to do this in a similar way as:
https://github.com/YousefED/typescript-json-schema/blob/master/test/schema.test.ts

Or do you require anything else?

**Comment by YousefED** [comment]
@Bnaya could you provide more input for this?

**Comment by Bnaya** [comment]
I'll try it, Thanks!
