### ISSUE TITLE
Missing properties in `Definition`

### ISSUE THREAD

**Issue by JemarJones** [YousefED/typescript-json-schema#310]
I may be missing something obvious here, but the `Definition` typescript type seems to be missing keys which are a part of the json schema standard. For example, [dependencies](https://json-schema.org/understanding-json-schema/reference/object.html#dependencies) or the [not](https://json-schema.org/understanding-json-schema/reference/combining.html#not) keyword.

**Comment by domoritz** [comment]
They may be part of the latest draft and not yet implemented. It would be good to switch to import this type from `@types/json-schema`. Can you send a PR?
