### ISSUE TITLE
Option to set default number type to integer

### ISSUE THREAD

**Issue by havogt** [YousefED/typescript-json-schema#315]
Is there an option to output all `number`s as integers by default? Then, specify some numbers as being floating point by annotation?

If not, would it be hard to implement? Could someone point me to the relevant lines?

**Comment by domoritz** [comment]
Json schema doesn't differentiate integers from floats and neither does typescript.

**Comment by havogt** [comment]
Thanks for your quick reply. I am completely new to json-schema and also typescript.

As far as I understand json-schema has `integer` and `number` type, whereas typescript only has `number`? Then my improved question would be to translate all typescript `number`s to json-schema `integer`s except the ones annotated with `@TJS-type number`. Would that make more sense? Thanks for helping me understand.

**Comment by domoritz** [comment]
You are absolutely right. Json schema does support integer. We could add an option to change the default. I'm happy to review a PR towards this goal.
