### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 282159468** [YousefED/typescript-json-schema#324]
ts-node t.ts
`xxx\node_modules\_typescript@3.7.2@typescript\lib\typescript.js:35954
            function trySymbolTable(symbols, ignoreQualification) {
                                   ^

RangeError: Maximum call stack size exceeded
`

// t.ts
const path = require('path')
const TJS = require('typescript-json-schema')
const glob = require('glob')

// optionally pass argument to schema generator
const settings = {
  required: true,
  uniqueNames: true,
  out: './a.json',
  strictNullChecks: true,
  include: ['**/*schema.ts'],
}

TJS.exec('./tsconfig.json', '*', settings)

// tsconfig.json
`{
  "compilerOptions": {
    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "ESNext",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    // "strict": true,                           /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    "paths": {
      "@/*": ["src/*"],
      "utils/*": ["src/utils/*"],
      "components/*": ["src/components/*"]
    },                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    "experimentalDecorators": true      /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
  }
}
`

**Comment by domoritz** [comment]
Could you describe what you’re trying to do, when the error occurs and what you have tried to fix it?

**Comment by itelo** [comment]
hey @domoritz, I am having the same issue

In my case, the problems occur when I use the types from React.

run.ts
```typescript
import { resolve } from "path";
import * as TJS from "typescript-json-schema";

const compilerOptions = {
  "target": "es5",
  "module": "esnext",
  "moduleResolution": "node",
  "resolveJsonModule": true,
  "lib": [
    "dom",
    "es2017",
    "es2015"
  ],
  "types": [
    "react"
  ],
  "declaration": true,
  "jsx": "react",
  "sourceMap": true,
  "strict": true,
  "strictNullChecks": false,
  "noImplicitAny": true,
  "esModuleInterop": true,
  "baseUrl": "./",
  "outDir": "lib",
};

// optionally pass argument to schema generator
const settings: TJS.PartialArgs = {};

const program = TJS.getProgramFromFiles([resolve("src/Elements/Button/interface.ts")], compilerOptions);

const generator = TJS.buildGenerator(program, settings);

generator.getSchemaForSymbol("ButtonInterface");
```

ButtonInterface with react
```typescript
import React from 'react';

export type ButtonInterface = 
React.ButtonHTMLAttributes<React.ReactNode> & 
 {
  className?: string;
  text?: string;
  full?: boolean;
  small?: boolean;
  outline?: boolean;
  noUnderline?: boolean;
}
```

ButtonInterface without react
```typescript
export type ButtonInterface = 
 {
  className?: string;
  text?: string;
  full?: boolean;
  small?: boolean;
  outline?: boolean;
  noUnderline?: boolean;
}
```

**Comment by domoritz** [comment]
Excellent. Those details will help with debugging if someone wants to pick this up. For now, I suggest that you increase the stack size for node to or try https://github.com/vega/ts-json-schema-generator.

**Comment by itelo** [comment]
@domoritz thank you for your quick answer, I tried to increase the stack size but now I got this error: 

```bash
[1]    7595 segmentation fault (core dumped)  node --stack_size=14000 test.js
```

I tried to use [ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) before, but when I add react I got:

```bash
Error: Unknown node "JSXElementConstructor<any>" (ts.SyntaxKind = 167) at .....
```

I also comment at [issue #209](https://github.com/vega/ts-json-schema-generator/issues/209)

**Comment by domoritz** [comment]
Thanks for trying. I don’t have the cycles to look into your specific case right now but I hope you find a solution that works for you.

**Comment by cdaringe** [comment]
i have this issue too.  i think it _may_ have something to do w/ recursive types, which are now permitted in typescript?

i debugged and found the stack exploding trying to model `Window` :|

```js
   [NUMERIC_INDEX_PATTERN]: this.getTypeDefinition(arrayType)
```

**Comment by cdaringe** [comment]
i moved my typedef as follows _out_ of the compile tree, and it began working again:

```ts
export type ExtendedWindow = (typeof window) & {
  someRandomGlobalOnTheWindow: bool
}
```

slap that little buddy into this and watch her break down!

**Comment by domoritz** [comment]
That’s a super useful test case. Thanks for sharing it.

**Comment by phaux** [comment]
Repro:

```ts
interface Test {
  children: TestChildren;
}

type TestChildren = TestChild | Array<TestChild | TestChildren>;

interface TestChild {
  type: "child";
}
```

```sh
npx typescript-json-schema tsconfig.json Test --include repro.ts
```

```
Maximum call stack size exceeded
```

**Comment by darkowic** [comment]
Works with really advanced React types! Check it here https://github.com/Guidewire/ts-to-json-schema-tests/blob/main/schemas/typescript-json-schema-ExampleProps.json

_yeah it's huge and you (we) probably don't want it but at least it works_
