### ISSUE TITLE
Error: type '*' not found(windows)

### ISSUE THREAD

**Issue by kerwin-ly** [YousefED/typescript-json-schema#334]
I used `typescript-json-schema` with `Angular7`. I encountered the issue that when i `npm run json`.The error occured in windows. But it works in mac v10.14.6.Can anyone explain it? Thx in advance.

error:
```
C:\Users\lizhi\AppData\Roaming\npm\node_modules\typescript-json-schema\dist\typescript-json-schema.js:842

throw new Error("type" + symbolName + "not found");
Error: type '*' not found
...
```

```json
"script": {
    "json": "typescript-json-schema './src/app/shared/interfaces/*.d.ts' '*' -o ./src/app/shared/interfaces/schema.json --id=api --required --strictNullChecks"

}
```

**Comment by qiuzhis** [comment]
please use cross-env in windows
cross-env typescript-json-schema 'src/dto/*.ts' '*'

**Comment by kerwin-ly** [comment]
ok, thx. @qiuzhis

**Comment by shubham49** [comment]
@qiuzhis how to resolve this if we are using through code?
