### ISSUE TITLE
Can't get this tool to work...

### ISSUE THREAD

**Issue by ghost** [YousefED/typescript-json-schema#345]
Please forgive me if this is stupid but I can't get this tool to work...
I've followed the instructions in the Read Me. This is what I did:

- ```npm install typescript-json-schema -g```
- ```typescript-json-schema "./src/shims/anotherTry.ts" "*"```

Doing that returns an empty schema: 
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
    }
}
```
I've tried doing it based on .tsconfig, like this:
```typescript-json-schema ./tsconfig.json "*"```

But I get this error:
```
var sourceFile = new SourceFileConstructor(290 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);
TypeError: Cannot read property 'length' of undefined
```

My typings file is as follows:
```
export class MyObject {
    /**
     * The size of the shape.
     *
     * @minimum 0
     * @TJS-type integer
     */
    public propA!: number;
    /**
     * The size of the shape.
     *
     * @minimum 0
     * @TJS-type integer
     */
    public propB!: number;
    public constructor() {
        this.propA = 0;
        this.propB = 0;
    }
}
```

My .tsconfig file is as follows:
```
{
    "compilerOptions": {
        "lib": [
            "es2015",
            "dom"
        ],
        
        "rootDir": "src",
        "outDir": "dist",

        // Module Resolution Options
        "typeRoots": [
            "node_modules/@types"
        ],

        // Experimental options
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
    },
    "references": [
        { "path": "../../shared/project" }
    ],
    "include": [
        "src/**/*"
    ]
}
```

Could you tell me what's wrong or what else I need to do that I haven't done?
Thank you in advance.

**Comment by RohanTalip** [comment]
Since the original poster (OP) is now a deleted / ghost user, should this issue be closed? (i.e. Since we can't ask the OP for a reproduction in a repository.)

**Comment by domoritz** [comment]
Yep.
