### ISSUE TITLE
How to specify the tsConfig.json file path

### ISSUE THREAD

**Issue by kalpeshhpatel** [YousefED/typescript-json-schema#346]
If you see here: https://github.com/vega/ts-json-schema-generator

There is an option to specify `tsConfig.json` path.

Wondering if we have similar option too?

**Comment by domoritz** [comment]
Yes. See the example in https://github.com/YousefED/typescript-json-schema#command-line.

**Comment by kalpeshhpatel** [comment]
Thanks for your response. Yes I have checked it. Basically I wanted to know how to specify in the programmatic way ( in TS file). I didn't find any examples of it. Can you please point me to the example of it. 

Thanks
