### ISSUE TITLE
Error while trying to generate schema

### ISSUE THREAD

**Issue by digeff** [YousefED/typescript-json-schema#35]
Any idea why I'm getting this:
λ typescript-json-schema myTSFile.ts MyMainType
npm/node_modules/typescript-json-schema/typescript-json-schema.js:120
                    else if (propertyType.getSymbol().getName() == "Array") {
                                                     ^

TypeError: Cannot read property 'getName' of undefined
    at JsonSchemaGenerator.getDefinitionForRootType (npm/node_modules/typescript-json-schema/typescript-json-schema.js:120:54)
    at JsonSchemaGenerator.getTypeDefinition (npm/node_modules/typescript-json-schema/typescript-json-schema.js:277:29)
    at npm/node_modules/typescript-json-schema/typescript-json-schema.js:90:34
    at Array.map (native)
    at JsonSchemaGenerator.getDefinitionForRootType (npm/node_modules/typescript-json-schema/typescript-json-schema.js:89:45)
    at JsonSchemaGenerator.getTypeDefinition (npm/node_modules/typescript-json-schema/typescript-json-schema.js:277:29)
    at JsonSchemaGenerator.getDefinitionForProperty (npm/node_modules/typescript-json-schema/typescript-json-schema.js:135:35)
    at npm/node_modules/typescript-json-schema/typescript-json-schema.js:237:41
    at Array.reduce (native)
    at JsonSchemaGenerator.getClassDefinition (npm/node_modules/typescript-json-schema/typescript-json-schema.js:235:49)

**Comment by YousefED** [comment]
Can you provide your ts file? Thanks!

**Comment by digeff** [comment]
`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

/* Event types used by the ProcessExecutionRecorder and ProcessExecutionSimulator */

export interface ITimedEvent {
    after: number;
}

export interface IStdOutEvent extends ITimedEvent {
    stdout: { data: string };
}

export interface IStdErrEvent extends ITimedEvent {
    stderr: { data: string };
}

export interface IErrorEvent extends ITimedEvent {
    error: { error: any };
}

export interface IExitEvent extends ITimedEvent {
    exit: { code: number };
}

export interface ICustomEvent extends ITimedEvent {
    custom: { lambda: () => Q.Promise<void> | void };
}

export type IEventArguments = IStdOutEvent | IStdErrEvent | IErrorEvent | IExitEvent | ICustomEvent;

export interface MachineConfiguration {
    os: { platform: string, release: string };
    android: {
        sdk: { tools: string, platformTools: string, buildTools: string, repositoryForSupportLibraries: string };
        intelHAXMEmulator: string;
        visualStudioEmulator: string;
    };
    reactNative: string;
}

export type PackagerStatus = "Running" | "NotRunning" | "TBD";

export type AndroidDeviceType = "AndroidSDKEmulatorDevice" | "VisualStudioEmulatorDevice" | "PhysicalDevice";

export interface IAndroidDevice {
    id: string;
    type: AndroidDeviceType;
    hardware: string;
    os: string;
    api: number;
    otherSpecs: string;
    appStatus: AppStatusInDevice;
}

export type IIOSDeviceType  = "TBD";

export type AppStatusInDevice = "NotInstalled" | "Installed" | "Running" | "Debugging" | "TBD";

export interface IIOSDevice {
    id: string;
    type: IIOSDeviceType;
    appStatus: AppStatusInDevice;
}

export interface MachineState {
    reactNative: { packager: PackagerStatus };
    devices: { android: IAndroidDevice[], ios: IIOSDevice[] };
}

interface ISpawnOptions {
    cwd?: string;
    stdio?: any;
    env?: any;
    detached?: boolean;
}

export interface ISpawnArguments {
    command: string;
    args: string[];
    options: ISpawnOptions;
}

export interface ProcessExecutionRecording {
    title: string;
    arguments: ISpawnArguments;
    date: Date;
    configuration: MachineConfiguration;
    state: MachineState;
    events: IEventArguments[];
}
`

**Comment by digeff** [comment]
I want to generate an schema for ProcessExecutionRecording

**Comment by YousefED** [comment]
@digeff this hould be closed by #41. Could you verify?
