### ISSUE TITLE
Defining "nullable"-Property --> "type": ["string", "null"]

### ISSUE THREAD

**Issue by sueess** [YousefED/typescript-json-schema#36]
Im wondering if there is any way to annotate the Typescript file so it generates something like that:
"type": ["string", "null"]. Can i somehow define this "nullable"-Property? Thanks a lot!

**Comment by YousefED** [comment]
Thanks. Will look into this in the next cycle - at this moment it's not possible yet.

**Comment by Justin-Credible** [comment]
I would also be interested in this. Since the `?` flag in TypeScript definitions indicates that the field may not be present (which is different from being present with a null value), does this mean we'd need an annotation to indicate a nullable field?

````
interface Something {
    /**
     * @schema-nullable
     */
    this: string;
}
````

**Comment by YousefED** [comment]
Let's wait for this until the `null` type makes it into typescript: https://github.com/Microsoft/TypeScript/pull/7140

Should make it more straightforward

**Comment by domoritz** [comment]
We have a blocked PR because of this issue https://github.com/vega/vega-lite/pull/1384 and it looks like https://github.com/Microsoft/TypeScript/pull/7140 was merged yesterday.

**Comment by YousefED** [comment]
Thanks. I suppose they'll be releasing typescript 2.0 with the feature soon. Unless you want to build against a nightly typescript version I'd suggest waiting for that before implementing?

**Comment by domoritz** [comment]
We can wait for the next ts release.
