### ISSUE TITLE
Remove support for TypeScript 3.5 and 3.6 and add 3.9 and 4.0?

### ISSUE THREAD

**Issue by RohanTalip** [YousefED/typescript-json-schema#373]
What versions of TypeScript should be supported?

My recent use of optional chaining (a TypeScript 3.7 feature) caused the build to break: https://travis-ci.org/github/YousefED/typescript-json-schema/builds

Should support for TypeScript 3.6 and 3.7 be removed and support for TypeScript 3.9 and 4.0 be added instead in the [.travis.yml](https://github.com/YousefED/typescript-json-schema/blob/a472741967ad77f8987d5e2df5968b2c42d3e471/.travis.yml) file?

**Comment by domoritz** [comment]
Done.

**Comment by RohanTalip** [comment]
Thanks!  I guess I should have also mentioned TypeScript 3.8 😃

**Comment by domoritz** [comment]
I added 3.8 in https://github.com/YousefED/typescript-json-schema/blob/master/.travis.yml

**Comment by RohanTalip** [comment]
Yep, I saw that at the time, thanks.  I was commenting more on me inadvertently leaving it out earlier.
