### ISSUE TITLE
No need to test multiple TypeScript versions

### ISSUE THREAD

**Issue by remcohaszing** [YousefED/typescript-json-schema#384]
The Travis test environment tests for various TypeScript versions. However, `typescript-json-schema` has a direct dependency on TypeScript. This means it can be safely assumed the TypeScript version in the version range of `package.json` is used.

If this package should have a dependency on `typescript`, the `TYPESCRIPT_VERSION` environment variables should be removed from `.travis.yml` to significantly reduce test time and save resources.

If the package should work with multiple TypeScript versions, `typescript` should be moved to `peerDependencies` using the version range `^3.7 || ^4` (or alternatively `>= 3.7`).

**Comment by domoritz** [comment]
Sounds like a good improvement. I'd be happy to review a pull request towards this goal. At the same time, let's switch to github actions since builds are faster and a lot more reliable.

**Comment by remcohaszing** [comment]
Do you prefer the solution of removing TypeScipt versions from the test  matrix or to move the `typescript` dependency to `peerDependencies`? I'm leaning towards the latter, but that would be a breaking change.

**Comment by domoritz** [comment]
I'd say for simplicity reasons, I'd be okay with just moving to the latest TS version. People can always stay on a previous version if they can't upgrade Typescript. 

Note that most of my attention is now on https://github.com/vega/ts-json-schema-generator so I'm not working on any major improvements for this repo but I will help to maintain it.
