### ISSUE TITLE
Top-level $ref in 0.44.0

### ISSUE THREAD

**Issue by joshkel** [YousefED/typescript-json-schema#391]
When I upgraded from typescript-json-schema 0.43.0 to 0.44.0, I noticed that AJV started giving a new warning when compiling the generated schema:

> $ref: keywords ignored in schema at path "#/properties/data/properties/pcList"

Sample TypeScript types:

```
interface Parent { name?: string; children: Child[]; }
interface Child { name?: string; parent?: Parent; }
```

The generated schema in 0.43.0 has a `definitions.Parent` section and also duplicates the `Parent` type's properties on the root schema. The generated schema in 0.44.0 has a top-level `"$ref": "#/definitions/Parent"` property. If I understand the discussions at https://github.com/ajv-validator/ajv/issues/1121 correctly, the top-level `$ref` object is technically invalid.

If I've misunderstood this, please let me know. Thanks!

**Comment by domoritz** [comment]
Hmm. Is [this](https://github.com/YousefED/typescript-json-schema/pull/383/files#r538811667) and instance of the problem? If so, we may need to revert the pull request.

**Comment by joshkel** [comment]
From doing some local experiments, I apparently had misunderstood; it looks like a top-level `$ref` can be valid; the fact that `type` is still there ([like you said](https://github.com/YousefED/typescript-json-schema/pull/383/files#r538811667)) is what's causing the problem.

I manually removed the top-level `type` from a sample recursive schema, and I'm able to compile and use it in AJV without errors.

**Comment by domoritz** [comment]
@darkowic and @joshkel do you think you can look into a fix for this bug?

**Comment by joshkel** [comment]
@domoritz, I took a stab at fixing it in #392. Feedback welcome; I'm pretty new to JSON Schema and may have missed something.
