### ISSUE TITLE
Top-level type annotation failed

### ISSUE THREAD

**Issue by ExcitedSpider** [YousefED/typescript-json-schema#394]
Reproduce:

```js
/** This annotation not  be include */
type Shape2 = { kind: string; size: number };
```

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "kind": {
            "type": "string"
        },
        "size": {
            "type": "number"
        }
    },
    "type": "object"
}
```

The annotation was given up.

**Comment by ExcitedSpider** [comment]
Hi, I found  something that maybe helpful. I forked the repo and marked.

In  method `JsonSchemaGenerator/getTypeDefinition`:
[commit diff](https://github.com/ExcitedSpider/typescript-json-schema/commit/d3438168e5a0e0b0fe15585f678ea277d9df607e)

**Comment by domoritz** [comment]
Please send a pull request.

**Comment by ExcitedSpider** [comment]
Hi, pull request sent.#395 
Some test case failed due to additional description.

**Comment by domoritz** [comment]
fixed by https://github.com/YousefED/typescript-json-schema/pull/395
