### ISSUE TITLE
Cannot find module '@/x' or its corresponding type declarations.

### ISSUE THREAD

**Issue by arturwita** [YousefED/typescript-json-schema#396]
Hi,
I'm using an alias for project's `src` directory, so my imports can be shortened. When I try to pass to `getSchemaForSymbol` an interface name, which uses custom types imported from module with an alias in it's path I'm getting the following error: `Cannot find module '@/<path>' or its corresponding type declarations.`. It seems that there is no support for that cases, or I'm doing something wrong.

For example:

PersonInterface:
```
import { AddressInterface } from "@/utils/interfaces";
import { GENDER } from "@/utils/enums";
// import { AddressInterface } from "../../../utils/interfaces"; // this would work
// import { GENDER } from "../../../utils/enums"; // this would work

export interface PersonInterface {
    name: string;
    age: number;
    address: AddressInterface;
    gender: GENDER;
}
```

index.ts:
```
import { getProgramFromFiles, buildGenerator, Definition } from "typescript-json-schema";
import glob from "tiny-glob";

const moduleAlias = require("module-alias");
moduleAlias.addAlias("@", __dirname);

const notWorking = async (typeName: string): Promise<Definition | undefined> => {
    const path = "src/services/**/interfaces/*.interface.ts"; // These files contain imports with an @ alias
    const files = await glob(path);
    const program = getProgramFromFiles(files);
    const generator = buildGenerator(program);

    return generator?.getSchemaForSymbol(typeName);
};

notWorking("PersonInterface")
    .then(json => console.log(`Undefined, due to alias imports: ${json}`))
    .catch(err => console.error(err))
```

Result:
```
src/services/user/interfaces/Person.interface.ts (1,34): Cannot find module '@/utils/interfaces' or its corresponding type declarations.

src/services/user/interfaces/Person.interface.ts (2,24): Cannot find module '@/utils/enums' or its corresponding type declarations.

Undefined, due to alias imports: undefined
```

I created a repo pointing out the problem. It can be found [here](https://github.com/arturwita/typescript-json-schema-alias-in-path). Is that possible to fix or get around it? 

Thanks

**Comment by sampotts** [comment]
Did you find a solution to this?

**Comment by ajosq** [comment]
@sampotts 

It will work fine if you use a tsconfig file for generating the schema instead of directly using the .ts files.

`typescript-json-schema \"libs/my-lib/tsconfig.schema.json\" \"*\"`

**Comment by ajosq** [comment]
> Did you find a solution to this?

It will work fine if you use a tsconfig file for generating the schema instead of directly using the .ts files.

typescript-json-schema \"libs/my-lib/tsconfig.schema.json\" \"*\"

**Comment by Aabishkar2** [comment]
Is there any way I can use this programmatically?

For example: where can I specify`tsconfig.json` in the following code

```
const notificationPath = resolve(
      './core/notifications',
      `${notificationTemplate.templateKey}Notification.ts`
    );
    const tsConfigPath = resolve('./', `tsconfig.json`);
    const program = TJS.getProgramFromFiles([notificationPath]);
    const schema = TJS.generateSchema(program, `${notificationTemplate.templateKey}Payload`);
```
