### ISSUE TITLE
Question: json-schema to typescript or typescript to json-jschema

### ISSUE THREAD

**Issue by no-more** [YousefED/typescript-json-schema#40]
Hi,

I'm new to typescript and json-schema and I would like to know which one is the more complete. I want to use the most complete one as base in order to generate the other one. At first glance I would think json-schema is more complete and polyvalent than typescript.

Could someone confirm this?

An idea: it would be great to be able to be bidirectionnal.

Thanks for your response and for your work on this project.

**Comment by YousefED** [comment]
You can't really compare both.
Typescript is a programming language, and JSON-schema is a schema for describing data.

What is your goal?

**Comment by no-more** [comment]
I need both typescript and json-schema version of my object definitions. But I want to maintain only one. I was wondering if I should write json-schema and then convert to typescript or if I should write typescript and then convert to json-schema.

**Comment by YousefED** [comment]
Hi,

I'm not currently aware of any good JSON-schema -> typescript converters. Of course I'm a little biased, but I'd recommend looking at this project, writing your objects in typescript, and then generating JSON Schema using TJS.

**Comment by no-more** [comment]
Thanks for all your replies,

I found one jsonschema->typescript tool but I haven't tried yet so I can't tell if it's a good one or not.

Do you think it would be possible to handle both way with your software ?

I need jsonschema to describe my API so I'm not sure if I can do it with typescript->jsonschema as it seems to better apply to object description only (I may be wrong).

Thanks.

**Comment by YousefED** [comment]
Typescript-JSON-Schema only converts from typescript -> json schema (one
direction)
