### ISSUE TITLE
Unsupported type void

### ISSUE THREAD

**Issue by TFTomSun** [YousefED/typescript-json-schema#401]
I try to generate a json schema for the typescript compiler. 
What I did so far:
-  npx typescript-json-schema "./node_modules/typescript/lib/tsserverlibrary.d.ts" "*" --ignoreErrors --excludePrivate

The error I get is:

> Unsupported type: void

I expected "--ignoreErrors" to simply emit everything else which is supported, but I don't get any other output

**Comment by domoritz** [comment]
The argument ignores only ts errors.

**Comment by ArthurFiorette** [comment]
To solve this problem, i'm removing this else block in the generated js file. _(At 0.51.0 is at line 477 of `typescript-json-schema.js`)_

https://github.com/YousefED/typescript-json-schema/blob/cb2fc7d8547b4cb2994b843d5b4d98e74f0eff0b/typescript-json-schema.ts#L682-L688
