### ISSUE TITLE
Generated schema uses type "default_1", "default_2" instead of class names

### ISSUE THREAD

**Issue by ballmw** [YousefED/typescript-json-schema#406]
I have a fairly deep schema and instead of getting class names in my schema I get "default_1", "default_2".  The classes that are having issues are ones that are used as Array<Type>, if I change them to a non-array (just Type) then they work.

Thanks for the help.

**Comment by domoritz** [comment]
Please try to create a minimal test case. Unfortunately, there isn't much anyone can help without these details.
