### ISSUE TITLE
Can't set multiple validationKeywords

### ISSUE THREAD

**Issue by bayerlse** [YousefED/typescript-json-schema#412]
Hey there! Very nice package.

Just have one question about `validationKeywords`:

How can I specify multiple `validationKeywords` ?

If I'm using: `--validationKeywords=collapsed` within cli it works great.
But when using something like: `--validationKeywords=collapsed,other`  it doesn't work at all.

Thanks in advance!

**Comment by domoritz** [comment]
Try adding the parameter multiple times.

**Comment by bayerlse** [comment]
Yes that worked, thanks!
