### ISSUE TITLE
Reuse generator?

### ISSUE THREAD

**Issue by murbanowicz** [YousefED/typescript-json-schema#415]
Hi,

Would you accept simple PR which would cache and reuse the generator during the same session?
Setting up the generator take few seconds, so in our case, when we use `generateSchema` over 100 times in test, it takes crazy long time, while with a 'hacked' solution, it took few seconds.

What I mean is doing something like this:
```typescript
let generator;
function generateSchema(program, fullTypeName, args, onlyIncludeFiles) {
    if (generator=== undefined) {
        generator= buildGenerator(program, args, onlyIncludeFiles);
    }
```

**Comment by domoritz** [comment]
Definitely!

**Comment by murbanowicz** [comment]
Cool. Will do that right now.
In our case, this "hack" decreased the test time from over 10m to about 15s.

**Comment by MarcusRiemer** [comment]
For the record: I had a similar issue and just "solved" the problem by generating a `Makefile` that could be called with `make -j` to launch as many processes as the system could meaningfully execute. A proper solution would be greatly appreciated.

**Comment by murbanowicz** [comment]
I will start simple PR and we can discuss/work together on that. 
I am fairly new here, but this issue was hurting our CI times so much, so I had to fix it in some way.

**Comment by murbanowicz** [comment]
Done: #416 - let's discuss it there.

**Comment by domoritz** [comment]
You could use the api to create a single generator. I don't think we can easily cache in the general case since inputs may change.

**Comment by murbanowicz** [comment]
I don't think I can or at least I cannot find the way.

We could cache based on params with a simple map <hash of params, generator> of generators maybe?

**Comment by domoritz** [comment]
```js
const generator = buildGenerator(program, args, onlyIncludeFiles);
```

Now you can reuse the `generator` variable for all your tests.

**Comment by murbanowicz** [comment]
Agree to some degree, but `generateSchema` does some other stuff that should stay there and not be repeated elsewhere.
Take a look at provided changes. It caches if it can with respect to changing input.

**Comment by domoritz** [comment]
How about we refactor the code to add a function that takes in a generator then? This way we allow composition but don't need to implement caching?

**Comment by murbanowicz** [comment]
That could work.
We can then accept optional generator as optional parameter but when it is not passed, it is still being created. Then, the caching is on user side, while there is no breaking change.

**Comment by domoritz** [comment]
That also sounds like a good option. Let's do that.

**Comment by murbanowicz** [comment]
Ok. Will do that in the evening or tomorrow.

**Comment by domoritz** [comment]
Mind if I do it real quick?

**Comment by GrantGryczan** [comment]
Hey @murbanowicz, what's the status on this? I have the same problem--needing to run generation on a lot of different files at the same time and it taking an extremely long duration.

**Comment by domoritz** [comment]
Do you still have time to send a pull request?

**Comment by murbanowicz** [comment]
I did it now: https://github.com/YousefED/typescript-json-schema/pull/418

The test case is missing as I do not have the time for that now, unfortunately. 
Please feel free to add it (should be possible)
