### ISSUE TITLE
Template Literal String Types are converted to an array schema instead of a string

### ISSUE THREAD

**Issue by ssc-hrep3** [YousefED/typescript-json-schema#426]
Template Literal String Types are converted to an array schema. They should, however, be converted to strings with a pattern matching the template literal (or at least to a regular string).

Here is an example of a template literal:
```
export const Test = `${number}`;
```
This type is then generated to:
```
{
  "type": "array",
  "items": {
    "type": "string"
  }
}
```
It should, however, at least be converted to this instead:
```
{
  "type": "string"
}
```
Even better would be if the template literal string is converted to a valid pattern. But this might be rather complex (joining regular expressions from types used within the template literal with the static string).
```
{
  "pattern": "^-?[1-9]\d*(?:\.\d+)?$"
  "type": "string"
}
```
A temporary workaround is to use the JSDoc annotation `@type string`, but unfortunately this does not work everywhere (i.e. when the template literal types are being used directly in arrays) due to another bug (see #425).

Version: `0.50.1`
Schema Generation Settings:
```
{
  ref: false,
  required: true,
  noExtraProps: true,
  validationKeywords: ['errorMessage'],
  titles: true,
  uniqueNames: true,
  rejectDateType: true
}
```

**Comment by olafur-palsson** [comment]
Related is using a template literal inside a template literal and getting `'TemplateLiteral' only refers to a type, but is being used as a value here.` can be fixed by updating.

**Comment by cstst** [comment]
Facing the same issue in `0.51.0`

**Comment by slhck** [comment]
@YousefED Any idea on how to solve this? Still getting this.

Note that as a workaround you may use [ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator):

```typescript
export type Test = {
    foo: `${number}x${number}`;
}
```

Then `ts-json-schema-generator --path test.ts` returns:

```json
{
  "$ref": "#/definitions/Test",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Test": {
      "additionalProperties": false,
      "properties": {
        "foo": {
          "type": "string"
        }
      },
      "required": [
        "foo"
      ],
      "type": "object"
    }
  }
}
```
