### ISSUE TITLE
Providing specific project files using glob

### ISSUE THREAD

**Issue by mayacoda** [YousefED/typescript-json-schema#43]
Tried to run the command in a subdirectory because I have multiple interfaces with the same name in different directories. I followed the instructions in the README and formatted the command thusly:

```shell
 typescript-json-schema src/mappings/draft-3/*.ts Workflow
```

However, I get this error.
```
                throw "type " + symbolName + " not found";
                ^
type src/mappings/draft-3/ArraySchema.ts not found
```

After some digging around in the code, I realized that the glob is expanded and supplied to the args, so the first x arguments of the command line are actually all the files that match the glob. This is actually [expected glob behavior in bash](http://www.tldp.org/LDP/abs/html/globbingref.html). The specified type is all the way at the end of the args array, and not the second argument as expected. 

My question: was this not the intended usage of a specific path or should the documentation be updated?

Thanks! Great work, by the way. 👍

**Comment by YousefED** [comment]
Thanks! Interesting, so bash automatically expands the *.ts into multiple filenames? If so, can you fix it by adding quotes around the path or another way to pass the file argument as string? TJS is using it's own globber, so we're not expecting multiple file inputs

**Comment by mayacoda** [comment]
It does work with quotes (not sure why it didn't the first time I tried it)!

Bash has this behavior regardless of context, for me. I'm on OS X El Capitan v 10.11.5. Maybe just specifying in the documentation that the path should be passed as a string would do the trick.

**Comment by YousefED** [comment]
Thanks
