### ISSUE TITLE
typescript-json-schema playground

### ISSUE THREAD

**Issue by orta** [YousefED/typescript-json-schema#430]
Hey folks, I built a TypeScript playground plugin which lets people try this module in the browser: https://twitter.com/orta/status/1420372927279771649

It required pulling out all of the node dependencies, so it's probably not worth trying to upstream my changes unless you're willing to take a few feature hits. Thought you might want to know, thanks for the library! 👍🏻

**Comment by domoritz** [comment]
Nice! have you considered using https://github.com/vega/ts-json-schema-generator, which is a bit more robust/better supported?

**Comment by orta** [comment]
I didn't, no, open to it if I ever decide to v2 the plugin though!

**Comment by domoritz** [comment]
Sounds good. 

Since there is no todo in the issue, I'll close it.
