### ISSUE TITLE
Runtime error when using programmatically with Rollup

### ISSUE THREAD

**Issue by restspace** [YousefED/typescript-json-schema#437]
Hi, I'm trying to use typescript-json-schema programatically in the context of a Typescript library for a CLI built with Rollup. I get an error at runtime in my bundle file at this line:
`glob_1.Glob;`
It says 'Cannot read property Glob of undefined'
This line comes from node_modules/glob/glob.js and seems to have been inserted at line 45 by bundling or Typescript compilation. This may well be an error in glob however I can't tell.
Versions from package_lock.json
glob: 7.1.7
typescript-json-schema: 0.51.0
typescript: 4.3.5
rollup: 2.56.3

**Comment by domoritz** [comment]
Please provide more details of what the issue with this library is. Right now, it's not actionable for us.

**Comment by restspace** [comment]
I will create a minimal project that causes this issue and get back to you. Thanks.

**Comment by domoritz** [comment]
Okay. I will close the issue for now and reopen when you provide more details.
