### ISSUE TITLE
Specifically allow additionalProperties on certain types?

### ISSUE THREAD

**Issue by MarcusRiemer** [YousefED/typescript-json-schema#44]
I usually run the generator using `--noExtraProps true` as I don't want the API these schemas are protecting to silently discard unknown data. This works great in general, but fails in one specific cornercase: In one type I need to allow extra fields as part of a general key-value store.

In Typescript, I expressed this as

    /**
     * A widget **requires** at least a type, all other fields are
     * mandated by deriving descriptions.
     */
    export interface WidgetDescription {
        type : string
        [x: string]: any 
    }

Adding additional fields to this works fine in code:

    const foo : WidgetDescription = {
        type : "test",
        additional : 2
    }

But the generated schema does not allow any additional properties:

        "WidgetDescription": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }

I am not quite sure how to correctly tackle this case in JSON schema. But from my understanding the presence of a property-specification like `[x: string]: any ` could translate to `additionalProperties: true`.

**Comment by YousefED** [comment]
Thanks markus. Does this help?

```
/**
         * @TJS-additionalProperties true
         */
export interface WidgetDescription {
    type : string
    [x: string]: any 
}```

**Comment by MarcusRiemer** [comment]
Sorry for the delay, this does solve my immediate problem, but I am still a little bit confused by the generated code. The new descriptions look like this:

    /**
     * A widget **requires** at least a type, all other fields are
     * mandated by deriving descriptions. As we don't necesarily
     * know all deriving classes at compile time (they could be
     * provided by a plugin) we poke a hole in the type system
     * here.
     * 
     * The following annotion is required to allow additional 
     * properties in the automatically generated JSON schema, see
     * https://github.com/YousefED/typescript-json-schema/issues/44
     * 
     * @TJS-additionalProperties true
     */
    export interface WidgetDescription {
        type : string
        [additional: string]: any 
    }
    
    /**
     * Describes a column that can host certain widgets
     */
    export interface ColumnDescription {
        width : number
        widgets : WidgetDescription[]
    }

The generated code places the `additionalProperties: true` property on the `ColumnDescription` hosting the `WidgetDescription`. For my use-case this is enough, but is this working as intended? I would expect the `additionalProperties: true` to pop up at the `WidgetDescription`.

    "ColumnDescription": {
        "type": "object",
        "properties": {
            "width": {
                "type": "number"
            },
            "widgets": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/WidgetDescription",
                    "description": "A widget **requires** at least a type, all other fields are\n\nmandated by deriving descriptions.\n\n\n\nThis annotation is required to allow additional properties in\n\nthe JSON schema, see https://github.com/YousefED/typescript-json-schema/issues/44",
                    "additionalProperties": true
                }
            }
        },
        "additionalProperties": false
    },
    "WidgetDescription": {
        "type": "object",
        "properties": {
            "type": {
                "type": "string"
            }
        },
        "additionalProperties": false
    },
