### ISSUE TITLE
Would you be willing to use Renovate Bot to keep dependencies up to date?

### ISSUE THREAD

**Issue by richardkazuomiller** [YousefED/typescript-json-schema#457]
There is a free tool called Renovate which automatically creates PRs for updating dependencies. There is a free hosted version and an open source version that can be self-hosted. It's quite a good time saver. I set up the hosted version in my fork so you can see it in action.

One of the reasons I'm asking is because I try to keep my version of TypeScript up to date, but if typescript-json-schema is still using an older version – in this case 4.4 when I want to upgrade my version of TypeScript to 4.5 – I need to keep using 4.4.

My fork: https://github.com/richardkazuomiller/typescript-json-schema/
Renovate: https://renovatebot.com/

**Comment by domoritz** [comment]
Please send a pull request to update typescript if you want a newer version.

**Comment by richardkazuomiller** [comment]
@domoritz Already done in #456. My suggestion is to add this tool so the PR gets created automatically in the future. Does this mean your answer to the question is "no"?

**Comment by domoritz** [comment]
I know dependabot and use it in Vega. But I don't want another tool for this repo since this library is in maintenance mode.
