### ISSUE TITLE
I can't use it for my ts files

### ISSUE THREAD

**Issue by gaofeng-lin** [YousefED/typescript-json-schema#468]
First question: I don't know what is TYPE . I always choose to use *
`typescript-json-schema project/directory/tsconfig.json TYPE`

This is my origin code: 
`export const userGroup = [
  {
    label: '用户组名称',
    type: ParamComponent.Input,
    key: 'usergroup_name',
    rules: [
      { required: true, message: '请输入用户组名' },
      { type: 'string', whitespace: true, message: '用户组名不能是空格' },
    ],
  },
  {
    label: '用户组描述',
    type: ParamComponent.Input,
    key: 'usergroup_desc',
    rules: [{ required: false, message: '请输入用户组描述' }],
  },
]`

But it's failed . Please help.

**Comment by gaofeng-lin** [comment]
@eventualbuddha

**Comment by domoritz** [comment]
Please be specific in your issue. Write a meaningful title and describe the error and what you tried.

**Comment by milahu** [comment]
> But it's failed

why?

in my case, `YousefED/typescript-json-schema` produced invalid schema, fixed by using [vega/ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator)

to validate schema, see https://github.com/YousefED/typescript-json-schema/issues/306#issuecomment-1085806346
