### ISSUE TITLE
Support "anyOf" for union type

### ISSUE THREAD

**Issue by kanitw** [YousefED/typescript-json-schema#47]
Currently union type always output "oneOf", but sometimes a JSON spec might satisfy multiple types of the TS interfaces.   Support using "anyOf" instead (and possibly by default would be useful). 

I remember @domoritz implemented this with `oneOf`, not sure how hard it is to use `anyOf`.

**Comment by mayacoda** [comment]
+1

Ran into this issue as well.

**Comment by domoritz** [comment]
I think `anyOf` as the default makes sense.
