### ISSUE TITLE
Update to typescript 2.0.

### ISSUE THREAD

**Issue by aindlq** [YousefED/typescript-json-schema#48]
Typescript 2.0 has been recently released, would it make sense to upgrade the library? I tried 2.0 locally, so far so good.

**Comment by YousefED** [comment]
I think this would make sense as soon as it's out of beta

**Comment by aindlq** [comment]
oh sorry, I was confused. They released 2.0.0 on npm https://libraries.io/npm/typescript/2.0.0, but apparently it is still kind of beta. It seems that actually stable will be 2.0.1.
