### ISSUE TITLE
Use programmatically

### ISSUE THREAD

**Issue by felixfbecker** [YousefED/typescript-json-schema#49]
I had an idea about instead of generating the schemas with the CLI, let the application parse his own interfaces and load the schema as objects at runtime, so they can be passed to https://www.npmjs.com/package/jsonschema. That would basically allow to do assertions at runtime against TypeScript interfaces instead of compile time. Is this possible?

**Comment by YousefED** [comment]
Hi Felix!

Should be possible as long as you have access to the TS code at runtime. See our test suite for how to call TJS programmatically: https://github.com/YousefED/typescript-json-schema/blob/master/test/schema.test.ts

**Comment by felixfbecker** [comment]
Hi, thanks for the quick response!
I just tried to `npm install typescript-json-schema` and import it, but TypeScript compaings that it cannot find the module. It seems like while you publish the TypeScript source file, you don't publish a `.d.ts` file.  Only the js and .d.ts file should be in the NPM package.

Then my second question: From the example you linked, it seems like you still write the schema to a file. Is it possible to generate the schema at runtime and only get the JSON schema as an object, without writing it to a file?

Maybe we could a "Using programmatically" section to the README 🙂

**Comment by dgreene1** [comment]
@felixfbecker this approach sounds great. I'm gonna give it a shot, and thank you for adding the "Using programmatically" section. That really helps.

What did you like or not like about this approach?
