### ISSUE TITLE
Is there any way to speed up the speed to generate json schema? The CLI mode runs 6 seconds on my mac m1 

### ISSUE THREAD

**Issue by grimmer0125** [YousefED/typescript-json-schema#499]
Hello, thank you for supplying this great library. My environment is 
- mac 12.4
- node: v16.13.1
- MacBook Pro w/ apple m1 pro
- CLI parameters: use `--include` to specify a single simple file

source TS file:
```
export class Error {
  code: number;
  message?: string;
}
```

It needs 6 seconds to generate. It is OK for my current usage. I'd like to know the possibility of enhancing the speed for the frequent use case.

**Comment by MarcusRiemer** [comment]
I switched to https://github.com/vega/ts-json-schema-generator quite a while ago and that offers `--no-type-check` which really helps. Apart from that you can have almost linear speedup by Just running it in parallel: once for each output file.

**Comment by domoritz** [comment]
@MarcusRiemer made some good suggestions.
