### ISSUE TITLE
Changes to lockfile and api.md if you run `yarn install` on a fresh checkout

### ISSUE THREAD

**Issue by rmehner** [YousefED/typescript-json-schema#542]
1. Clone repo
2. Run `yarn install`

See these changes:  https://gist.github.com/rmehner/e03b680c5685905099e43c9ec1231d9e (as gist, since the diff is too large to be pasted here)

The changes to `yarn.lock` most likely happen because someone used `npm` instead of `yarn` in this case and the changes have been committed then. Fix would be easy: just commit the changed file, after that, no one should see these changes anymore. Just need to make sure that people keep using yarn there.

Was a bit confused by it when I tried to contribute, so might be good to fix that :)

Thanks!

**Comment by domoritz** [comment]
Thank you for the issue. Do you want to send a pull request?
