### ISSUE TITLE
Add optional flag to convert const to single value enums

### ISSUE THREAD

**Issue by gassiss** [YousefED/typescript-json-schema#570]
Hello! 👋 

We rely on this library to generate JSON schemas to use with OpenAPI. Unfortunately, [this PR](https://github.com/YousefED/typescript-json-schema/pull/535) introduced some breaking changes for us, as OpenAPI straight up doesn't allow constant values, and the workaround was to do exactly what the PR fixed.

Any chance we can get that behaviour back behind a feature flag? Seems like a pretty simple change, I have it working locally for our use case and would be happy to open a PR if that's OK.

Thanks for your work on this!

**Comment by domoritz** [comment]
Happy to accept a pull request. Maybe we can add a flag for openapi. If I recall correctly, there were some other requests that you can search for.

**Comment by gassiss** [comment]
nice! I'll open a PR for review soon. Thanks for the quick feedback!
