### ISSUE TITLE
Enhancement: Docusaurus documentation ?

### ISSUE THREAD

**Issue by jy95** [YousefED/typescript-json-schema#586]
Hello,

Thanks for your work maintaining this tool.
I noticed that projets has bunch of [tests](https://github.com/YousefED/typescript-json-schema/tree/master/test/programs) and it would be nice to have a [Docusaurus documentation website](https://docusaurus.io/) showcasting input / output / config efficiently like this with tabs : 

![image](https://github.com/vega/ts-json-schema-generator/assets/9306961/b4109c7b-15fd-4d11-a737-2e0f1a328b97)

What do you think ?

Kind regards

Notice : Screenshot is coming from [docusaurus-json-schema-plugin](https://github.com/jy95/docusaurus-json-schema-plugin) project where I had a similar need.

**Comment by domoritz** [comment]
I don't actually update this package anymore as I shifted to https://github.com/vega/ts-json-schema-generator a few years ago. It would be awesome to add docusaurus to https://github.com/vega/ts-json-schema-generator and I would be happy to review a pull request.
