### ISSUE TITLE
Functionality in Pull Request 54 has been Overwritten?

### ISSUE THREAD

**Issue by low-ghost** [YousefED/typescript-json-schema#62]
[This pull request](https://github.com/YousefED/typescript-json-schema/pull/54) allowed passing in arbitrary keywords that would be accepted and added to the generated schema. This functionality appears to be missing from master now. Am I missing a new way of passing in these kinds of fields (e.g. faker)? Unless I am mistaken, they are now picked up as 'otherAnnotation' and left out of the process

**Comment by low-ghost** [comment]
Nevermind, guess I just never noticed that it was closed and not merged. I'll just keep a separate branch if this isn't functionality you intend to implement.

**Comment by domoritz** [comment]
I don't see a diff in #54

**Comment by low-ghost** [comment]
Well, that'd be why then. Must have made a pr against the wrong branch? Anyhow, there have been significant changes, so I'll recreate this pr against a new branch to avoid conflicts. In a bit...
