### ISSUE TITLE
Accessing the JsonSchemaGenerator class

### ISSUE THREAD

**Issue by benbabic** [YousefED/typescript-json-schema#65]
Hey guys,

I'm working with a custom version of the typescript compiler and was hoping to generate schema for certain types - but not all. I already have access to the `ts.Type` I want a schema for and I used  `JsonSchemaGenerator.getSchemaForSymbols` to get it but I had to modify your code to export the `JsonSchemaGenerator` class.

Do you see something inherently wrong with this approach ? If not, would you welcome a pull request changing the `TJS` module to export the `JsonSchemaGenerator` class so it can be accessed from the outside ?

**Comment by domoritz** [comment]
Something like https://github.com/YousefED/typescript-json-schema/pull/50? I'm just waiting for a rebase and will merge.

**Comment by benbabic** [comment]
I'm not quite sure this is the same but I might be wrong.

The change I was thinking about was to changes the visibility of the `JsonSchemaGenerator` class to be public - visible from outside typescript-json-schema.ts. 

From the one commit on the pull request It seems that the class is not exported (typescript-json-schema.ts:24).

I don't mind submitting a PR as the change is literally just one word and you can then tell me what you think of it - i might not have time to do this today though.

**Comment by domoritz** [comment]
Sure. I just won't guarantee that interns stay constant.

**Comment by domoritz** [comment]
@benbabic Ping. It should be easy to add the export now.
