### ISSUE TITLE
how to force a field to be a specific type?

### ISSUE THREAD

**Issue by benny-medflyt** [YousefED/typescript-json-schema#82]
I am trying to do something like:

```typescript
/**
* How to force a Widget to be encoded as number?
*
* @type number
*/
export interface Widget {}

export interface House {
    name: string;

    mainWidget: Widget;
    otherWidgets: Widget[];
}
```

So that the `mainWidget` field is encoded as a regular "number", and also `otherWidgets` will be an array of numbers.

In other words I would like to get the following schema:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "name": {
            "type": "string"
        },
        "mainWidget": {
            "type": "number"
        },
        "otherWidgets": {
            "items": {
                "type": "number"
            },
            "type": "array"
        }
    },
    "required": [
        "name",
        "mainWidget",
        "otherWidgets"
    ],
    "type": "object"
}
```

thank you

**Comment by domoritz** [comment]
Yes, you have to use:

```ts
/** @TJS-type integer */
```

See https://github.com/Microsoft/TypeScript/issues/13498 for the reason why this is necessary.

**Comment by benny-medflyt** [comment]
Hi, I tried using `@TJS-type` but I don't think it helps me in this case

**Comment by domoritz** [comment]
Can you send a pull request with a test case? Thanks!

**Comment by benny-medflyt** [comment]
Sent as #83

**Comment by domoritz** [comment]
The issue is that we try to infer types and defintions and overriding properties can have weird effects. I added some code so it works for types but I'm not convinced that it's a good idea in general to let users override properties.

**Comment by benny-medflyt** [comment]
Thanks, this is amazing! But i have found a small bug i think when importing type from another module. I've added another test case in #84

**Comment by domoritz** [comment]
Thanks @benny-medflyt! Do you think you could look into a fix for the issue?

**Comment by benny-medflyt** [comment]
I'm not familiar with typescript-json-schema source code, but maybe in a few days I'll have time to try to figure this out
