### ISSUE TITLE
Override type feature ?

### ISSUE THREAD

**Issue by mmc41** [YousefED/typescript-json-schema#88]
I would like to be able to override input and output when generating schemas. I am not sure how it should look like in details (or how to implement such a feature):

**Overriding input:**
I have some complex typescript definitions, where I would like to dynamically replace one typescript type definition with another when generating schemas (for instance dynamically replacing a specific typescript type "xxx" with type "any") in the input for the generated schema.

**Overriding output**
I have some typescript definitions where a corresponding schema file already exist that is official or better at representing json schema definitions for a property in a typescript interface. For instance, If I use an unofficial typescript type to represent a json schema like [this one](https://github.com/mmc41/json-schema-js-gui-model/blob/master/src/dependencies/json-schema.ts), I would like property type references for this JsonSchema type to be converted into one of the official json schema meta schema files around rather than typescript-json-schema producing it's own unofficial version (this is likely not be 100% correct anyway.

**Comment by otgerrogla** [comment]
I added a function ``setSchemaOverride`` to the ``JsonGeneratorClass``.
I'm not sure if I understood correctly what you mean, but with this you could do:

```typescript
   generator.setSchemaOverride("SomeComplextype", {});
   // Now SomeComplexType would act as if defined as "any"
```

```typescript
   generator.setSchemaOverride("JsonSchema", { "$ref": "http://json-schema.org/schema#" });
   // JsonSchema references now the official spec
```

**Comment by mmc41** [comment]
@otgerrogla That is brilliant! Does indeed look like it would solve my use cases.

Maybe generateSchema could also add an optional parameter (a map) that can collect all the schema overrides so generateSchema (which I am currently using) can support this functionality as well. 

I look forward to try this neat feature when a new npm is released.

**Comment by mmc41** [comment]
Or the Arguments map for could get a new key were the value is in-itself a map between types and overwrites ?

**Comment by domoritz** [comment]
Fixed and published. Please create a new issue for extensions.

**Comment by mmc41** [comment]
@otgerrogla Just tried setSchemaOverride on new newly published npm. Works beautifully. Thanks!
