### ISSUE TITLE
@type support is a hack

### ISSUE THREAD

**Issue by domoritz** [YousefED/typescript-json-schema#91]
I don't like [this patch](https://github.com/YousefED/typescript-json-schema/commit/d1ab21886313be2bfaebc10afcb3f379bf6f1416). It works around the compiler with a hack. I prefer if we roll this back and ask people to use `@TJS-type` instead.

Comments @otgerrogla?

**Comment by domoritz** [comment]
I've files an issue with Typescript a while back https://github.com/Microsoft/TypeScript/issues/13498. I'd much prefer a fix in the compiler.

**Comment by otgerrogla** [comment]
Yes, it was meant as a temporary hack to keep backwards compatibility.

In fact I'm worried about conflicts by using ``@type``, as it was meant for defining a different type for the schema than the one declared in Typescript, but now Typescript uses it internally which might lead to some issues. I think we should rather drop support for ``@type`` completely.

**Comment by domoritz** [comment]
I'd be fine with that. It is important to be able to say that a number is actually an integer or a string is a special type such as color but everything beyond this can break many things. 

Okay, how about we drop support for `@type` and do a best effort to support `@TJS-type`? To do this, we rollback the change and make sure to document how to annotate in comments.

**Comment by otgerrogla** [comment]
Ok, I rolled back the commit.

**Comment by domoritz** [comment]
Thanks! I'll add something to the readme. can you look into https://github.com/YousefED/typescript-json-schema/issues/90?

**Comment by domoritz** [comment]
@otgerrogla I've added notes to the readme. In the future, let's not include the built js and js.map in the the repo until we actually make a new release.

**Comment by nidi3** [comment]
Thanks for the readme. I was not aware of TJS-type annotation.

**Comment by domoritz** [comment]
@nidi3 You're welcome. We haven't been very good about documenting all the features until now but I hope things are clearer now.
