### ISSUE TITLE
Incorrect interaction with TypeScript "Mapped types" feature

### ISSUE THREAD

**Issue by benny-medflyt** [YousefED/typescript-json-schema#95]
TypeScript has a new feature (2.1) called "Mapped Types".

The example from the release notes:

```typescript
interface Person {
    name: string;
    age: number;
    location: string;
}
```

If we want a type that looks like this:

```typescript
interface PartialPerson {
    name?: string;
    age?: number;
    location?: string;
}
```

then instead of writing out all the fields, you can use:

```typescript
type PartialPerson2 = Partial<Person>;
```

When typescript-json-schema is run on the manually written `PartialPerson` type, it works great, but when run on the "magically" created `PartialPerson2` it produces the wrong JSON schema. (`PartialPerson` and `PartialPerson2` should be equivalent)

**Comment by domoritz** [comment]
These things are tricky because we need special cases in the code. I don't think the Typescript compiler has a way to resolve generics before we get the types.

**Comment by benny-medflyt** [comment]
Thanks for the explanation. I don't know about the internals of the TypeScript compiler, but it looks like at least `tsserver` is able to get detailed information about the type:

<img width="217" alt="screen" src="https://cloud.githubusercontent.com/assets/24827547/22705929/160614ce-ed76-11e6-9acc-aace458e42bf.png">

**Comment by domoritz** [comment]
Interesting. It may be a good idea to use the tsserver then instead of calling compiler internal functions.

**Comment by domoritz** [comment]
The server calls `getTypeDefinitionAtPosition` https://github.com/Microsoft/TypeScript/blob/5644b013c999709be0b75508d829449f058f17c1/src/server/session.ts#L470

**Comment by TimMensch** [comment]
I just ran into this right now. FWIW you don't need to use generics to hit this bug:

```
declare interface DiceSpec {
    basic : number;
    air : number;
    fire : number;
    water : number;
    earth : number;
}

type MaybeDiceSpec = {
    [ P in keyof DiceSpec ]?: DiceSpec[ P ];
};
```

The MaybeDiceSpec comes out as an empty object. Just like above, tsserver can look at the type and see exactly what the derived type looks like.

**Comment by domoritz** [comment]
@TimMensch Yeah, keyof is a very new feature that is not supported yet. Again, I think if we can somehow use the language server, we might be able to not have to manually adjust the library every single time ts adds a new feature.

**Comment by HoldYourWaffle** [comment]
Has this been fixed yet? I'm having some issues generating schemas and this *might* be one of them but I'm not completely sure...

**Comment by domoritz** [comment]
Yep, the example in https://github.com/YousefED/typescript-json-schema/issues/95#issuecomment-278149555 as well as the original spec in https://github.com/YousefED/typescript-json-schema/issues/95#issue-205615094 work for me.
