### ISSUE TITLE
Override property feature ?

### ISSUE THREAD

**Issue by mmc41** [YousefED/typescript-json-schema#96]
Just like the nice setSchemaOverride feature (by @otgerrogla) allows types to be overridden, I would like specific properties to be overridden as well. For instance, in the below type, I would like the '**id**' string (and NOT the 'description' string) to conform to a regular expression that describes how a string identifier looks like exactly. 

I can't express string constrains in typescript or in typescript-json-schema. I guess, one way to do this, would be some kind of setPropertyOverride function where I could specify my own json schema string definition with a json schema 'pattern' property inside?

```
export interface Person {
    id: string; // Should conform to a specific regular expression.
   description: string // This is a free form string
};
```

**Comment by domoritz** [comment]
I'm confused. You can use something like this

```ts
export interface Person {
    /**
     * @pattern ^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$
     */
    id: string; // Should conform to a specific regular expression.
   description: string // This is a free form string
};
```

**Comment by mmc41** [comment]
Thanks. The docs only mention @TJS-type so I did not see the @pattern option.
Works fine, so I will close this. Thanks again!

**Comment by domoritz** [comment]
Here is the list of keywords: https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts#L74
