### ISSUE TITLE
Upgrade to typescript v2.4 ?

### ISSUE THREAD

**Issue by mmc41** [YousefED/typescript-json-schema#99]
I noticed that the current version of typescript-json-schema is pinned to 2.1.x versions of typescript. Can it be upgraded to the new v2.2.0?

**Comment by domoritz** [comment]
As long as the typescript team has not made significant changes to the internal APIs, this should be possible.

**Comment by domoritz** [comment]
Actually, I looked at it for a few minutes and noticed that they removed some APIs related to js docs. 

```
> typescript-json-schema@0.9.1 build /Users/domoritz/Developer/UW/typescript-json-schema
> tsc -p .

typescript-json-schema.ts(140,31): error TS2339: Property 'getJsDocTags' does not exist on type 'Symbol'.
typescript-json-schema.ts(141,24): error TS7006: Parameter 'doc' implicitly has an 'any' type.
```

I don't have time to look into it right now but it should be possible to change how we get annotations and upgrade to ts 2.2.

**Comment by benbabic** [comment]
Just as a heads up, I was looking into the changes to the compiler for ts 2.2 and it seems that `ts.Symbol.members` that your code references [here](https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts#L478l) is now a map defined as such:
```typescript
 interface Symbol {
        flags: SymbolFlags;
        name: string;
        declarations?: Declaration[];
        valueDeclaration?: Declaration;
        members?: SymbolTable;
        exports?: SymbolTable;
        globalExports?: SymbolTable;
}
type SymbolTable = Map<Symbol>;
```

Also, I'm a bit confused by that but [MDN docs for Map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map) seem to suggest that `.length` is allways 0 for a map and that `.size` is holding what would correspond to `Array.length`.

So `clazz.members.length === 1` might not throw any error and simply be always false.

Hope this helps you move to 2.2 ...

**Comment by domoritz** [comment]
Thanks for the heads up @benbabic. I would have probably missed this. 

The main thing I'm worried about is the changes in the API around JsDocs. I wish we could use the language service somehow instead of using compiler internal methods. However, I don't have the time to look into it at least for another month.

**Comment by mmc41** [comment]
@domoritz Has this issue been raised with the TS team - maybe they need to know there is a need to access the JsDocs API ?

**Comment by navossoc** [comment]
@mmc41 Kinda...
Take a look at: https://github.com/Microsoft/TypeScript/issues/13498

**Comment by wiktor-k** [comment]
Sadly the TypeScript compiler does not support [design-time decorators](https://github.com/Microsoft/TypeScript/issues/2900) yet. They seem like a perfect fit for JSON Schema related annotations.

**Comment by navossoc** [comment]
Well...

I'm using [typeorm](https://github.com/typeorm/typeorm) and they use [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) to extract some additional data.
So we can do fancy things like this:

```ts
import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";

@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 500
    })
    name: string;

    @Column("text")
    description: string;

    @Column()
    fileName: string;

    @Column("int")
    views: number;

    @Column()
    isPublished: boolean;
}
```

I know it will be a breaking change, but at least seems to be more "stable".
Take a look.

**Comment by domoritz** [comment]
Can you put this in a separate issue so we can discuss it?

**Comment by wiggisser** [comment]
What about support for 'object' type which was introduced in version 2.2

**Comment by domoritz** [comment]
This in another thing to take care of when we transition to 2.2. I don't
thing it will be too hard compared to the changes necessary to support
jsdocs.

**Comment by mmc41** [comment]
FYI: In the mean time TS 2.3.1 has been released.

**Comment by domoritz** [comment]
I just updated the title of this issue ;-)

I hope to find some time to do the upgrade soon but there are a few more pressing issues that I need to get to. I'm happy to review pull requests, though!

**Comment by nfour** [comment]
@domoritz I'd be willing to contribute a PR.

Is there any info you could share on the migration process you've already accumulated? If not I understand it's just a blind debug process.

**Comment by domoritz** [comment]
That would be amazing! I think most of what I know is in this issue. I've also recently put a lot of effort into https://github.com/vega/typescript-to-json-schema as I was having too many problems with aliases. Maybe you find some useful things in there. 

Oh, and https://astexplorer.net/ if super useful.

**Comment by nfour** [comment]
@domoritz that looks like a lot of changes, I think I'll wait until you've got that merged first :+1: . I'm getting by with --ignoreErrors for now.

**Comment by mmc41** [comment]
FYI: In the mean time TS 2.4 has been released... Updating title.

**Comment by mmc41** [comment]
@domoritz Wunderfull news! Do you plan to release a new version (npm) with this soon ?
